/* Sowa9 v4 - complete local driver rotation engine */
'use strict';
const KEY='sowa9.v4';
const DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const DRIVERS=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const DEFAULT_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز طبي',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',name:'دنيا برك',seq:1,day:'الأحد',need:2,night:false,periods:[['12:00','22:00']],note:'نقل مشترك.'},
{id:'garden',name:'غاردن سيتي',seq:2,day:'الأحد',need:2,night:true,periods:[['17:00','00:00']],note:'نقل مشترك.'},
{id:'bahja',name:'البحر — بهجة',seq:3,day:'الثلاثاء',need:1,night:false,periods:[['09:00','22:00']],note:'خارجي ومتعب بسبب الحرارة؛ بهجة أصعب. لا تُحسب كعمل ليلي.'},
{id:'club',name:'البحر — كلوب',seq:4,day:'الثلاثاء',need:3,night:false,periods:[['12:00','22:00']],note:'خارجي ومتعب بسبب الحرارة. لا تُحسب كعمل ليلي.'},
{id:'bondage',name:'بونداج زرالدة',seq:5,day:'الأربعاء',need:2,night:false,periods:[['04:30','10:00']],note:'نقل مشترك.'},
{id:'guard',name:'حراسة',seq:6,day:'الأربعاء',need:1,night:true,periods:[['17:00','00:00']],note:'داخلي ومريح، لكنه يُحسب عملًا ليليًا.'},
{id:'raids',name:'مداهمات',seq:7,day:'الخميس',need:2,night:true,periods:[['19:30','05:00']],note:'عمل خارجي ليلي.'},
{id:'delivery',name:'توصيل',seq:8,day:'الخميس',need:1,night:false,periods:[['20:00','21:30'],['06:30','08:00']],note:'فترتان منفصلتان.'},
{id:'barajat',name:'براجات',seq:9,day:'الجمعة',need:1,night:false,periods:[['06:00','12:00']],note:'داخلي ومريح.'},
{id:'forest',name:'الغابة',seq:10,day:'الجمعة',need:4,night:false,periods:[],note:'24 ساعة؛ أربعة سواق: Alpha وMO.'}
];
const FOREST={
 Alpha:{roles:[
  {id:'alpha_pair',label:'Alpha — بداية + نهاية',segments:[['17:00','23:00'],['11:00','17:00']],paired:true},
  {id:'alpha_middle',label:'Alpha — الوسط',segments:[['05:00','11:00']],paired:false}
 ]},
 MO:{roles:[
  {id:'mo_pair',label:'MO — بداية + صباح',segments:[['17:00','22:00'],['07:00','12:00']],paired:true},
  {id:'mo_end',label:'MO — النهاية',segments:[['12:00','17:00']],paired:false}
 ]}
};
function fresh(){return {version:4,drivers:DRIVERS.map((name,i)=>({id:i+1,name,status:DEFAULT_STATUS[name]})),weeks:[],assignments:[],loans:[],missed:[],events:[]};}
let db=(()=>{try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'null')||{})}catch(e){return fresh()}})();
if(!Array.isArray(db.drivers)||!db.drivers.length)db=fresh();
function save(){localStorage.setItem(KEY,JSON.stringify(db));render();}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random())}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';clearTimeout(window._toast);window._toast=setTimeout(()=>x.style.display='none',2200)}
function dateOnly(v){return new Date(v+'T12:00:00')}
function iso(d){return d.toISOString().slice(0,10)}
function sundayOf(s){const d=dateOnly(s);d.setDate(d.getDate()-d.getDay());return iso(d)}
function dayDate(start,day){const d=dateOnly(start);d.setDate(d.getDate()+DAYS.indexOf(day));return iso(d)}
function dt(date,time,next=false){const d=new Date(date+'T'+time+':00');if(next)d.setDate(d.getDate()+1);return d}
function fmt(v){return new Date(v).toLocaleString('ar-DZ',{dateStyle:'short',timeStyle:'short'})}
function hours(a,b){return Math.max(0,(new Date(b)-new Date(a))/3600000)}
function durationText(h){const m=Math.round(h*60),d=Math.floor(m/1440),r=m%1440,hh=Math.floor(r/60),mm=r%60;return `${d?d+' يوم ':''}${hh} ساعة ${mm} دقيقة`}
function mission(id){return MISSIONS.find(x=>x.id===id)}
function currentWeek(){return db.weeks[0]||null}
function active(){return db.drivers.filter(d=>d.status==='متاح'||d.status==='مستعار')}
function allHistory(id){return db.assignments.filter(a=>a.driverId===id).sort((a,b)=>new Date(a.start)-new Date(b.start))}
function lastOverall(id){return allHistory(id).at(-1)||null}
function lastExact(id,missionId,role,forestType){return db.assignments.filter(a=>a.driverId===id&&a.missionId===missionId&&(!role||a.role===role)&&(!forestType||a.forestType===forestType)).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]||null}
function lastMission(id,missionId){return db.assignments.filter(a=>a.driverId===id&&a.missionId===missionId).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]||null}
function lastExchange(id){return db.loans.filter(x=>x.driverId===id).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]||null}
function restBefore(id,start){const h=allHistory(id).filter(a=>new Date(a.end)<=new Date(start));if(!h.length)return null;const p=h.at(-1);return {previous:p,from:p.end,to:start,hours:hours(p.end,start)} }
function unresolvedMissed(id,missionId,role,forestType){return db.missed.filter(x=>x.driverId===id&&x.missionId===missionId&&(!role||x.role===role)&&(!forestType||x.forestType===forestType)&&!x.resolved)}
function weekFor(start){return db.weeks.find(w=>w.start===sundayOf(start))||null}
function createWeek(start){start=sundayOf(start);if(db.weeks.some(w=>w.start===start)){toast('الأسبوع موجود');return}db.weeks.unshift({id:uid(),start,createdAt:new Date().toISOString()});save();toast('تم إنشاء الأسبوع');}
function periodForMission(m,w){const base=dayDate(w.start,m.day);return m.periods.map((p,i)=>({start:dt(base,p[0],false),end:dt(base,p[1],p[1]<'12:00'&&p[0]>'12:00')}));}
function forestPeriods(w,type,roleId){const base=dayDate(w.start,'الجمعة'),r=FOREST[type].roles.find(x=>x.id===roleId);return r.segments.map((p,i)=>{let start=dt(base,p[0],false),end=dt(base,p[1],p[1]<'12:00'&&p[0]>'12:00');if(i>0||p[0]<'17:00')start.setDate(start.getDate()+1);if(i>0||p[0]<'17:00')end.setDate(end.getDate()+1);return {start,end};});}
function candidates(missionId,role='',forestType='',start){const nowStart=start||new Date();return active().map(d=>{const exact=lastExact(d.id,missionId,role,forestType),same=lastMission(d.id,missionId),overall=lastOverall(d.id),miss=unresolvedMissed(d.id,missionId,role,forestType),rest=restBefore(d.id,nowStart),exchange=lastExchange(d.id);return {d,exact,same,overall,missed:miss.length,rest,exchange,count:db.assignments.filter(a=>a.driverId===d.id&&a.missionId===missionId).length}}).sort((a,b)=>{
 if(a.missed!==b.missed)return b.missed-a.missed;
 if(!a.exact&&!b.exact){if(!a.same&&!b.same)return a.d.id-b.d.id;if(!a.same)return -1;if(!b.same)return 1}
 if(!a.exact)return -1;if(!b.exact)return 1;
 const t=new Date(a.exact.start)-new Date(b.exact.start);if(t)return t;
 if(a.count!==b.count)return a.count-b.count;
 const ar=a.rest?.hours??Infinity,br=b.rest?.hours??Infinity;if(ar!==br)return br-ar;
 const ao=a.overall?new Date(a.overall.start).getTime():-Infinity,bo=b.overall?new Date(b.overall.start).getTime():-Infinity;return ao-bo;
});}
function addAssignment({weekId,missionId,driverId,role='',forestType='',start,end,part=1,linkedId=null,planned=false,replacement=false,reason=''}){db.assignments.push({id:uid(),weekId,missionId,driverId,role,forestType,start:new Date(start).toISOString(),end:new Date(end).toISOString(),part,linkedId,planned,replacement,reason,createdAt:new Date().toISOString()});}
function recordMission(m,w,driverId,reason=''){const ps=periodForMission(m,w);const linked=uid();ps.forEach((p,i)=>addAssignment({weekId:w.id,missionId:m.id,driverId,start:p.start,end:p.end,part:i+1,linkedId:ps.length>1?linked:null,reason}));}
function recordForest(w,type,roleId,driverId,reason=''){const ps=forestPeriods(w,type,roleId),linked=ps.length>1?uid():null;ps.forEach((p,i)=>addAssignment({weekId:w.id,missionId:'forest',driverId,role:roleId,forestType:type,start:p.start,end:p.end,part:i+1,linkedId:linked,reason}));}
function addMissedTurn(w,missionId,driverId,role,forestType,reason){db.missed.push({id:uid(),weekId:w.id,missionId,driverId,role,forestType,reason,resolved:false,date:new Date().toISOString()});}
function logLoan(driverId,type,otherTeam,missionName,start,end,reason){db.loans.push({id:uid(),driverId,type,otherTeam,missionName,start,end,date:new Date().toISOString(),reason});save();}
function markStatus(id,status){const d=db.drivers.find(x=>x.id===id);if(!d)return;d.status=status;db.events.push({id:uid(),type:'status',driverId:id,status,date:new Date().toISOString()});save();}
function compareDriver(id){const d=db.drivers.find(x=>x.id===id),h=allHistory(id);let rows=[];for(const a of h){const r=restBefore(id,a.start);rows.push({a,r});}return {d,rows};}
function renderDashboard(){const w=currentWeek();return `<h2>لوحة القيادة</h2><div class="grid"><div class="card"><h3>الأسبوع الحالي</h3><div class="metric">${w?esc(w.start):'—'}</div><p class="muted">يعاد الحساب أسبوعيًا، ولا يحذف التاريخ.</p></div><div class="card"><h3>السواق المتاحون</h3><div class="metric">${active().length}</div></div><div class="card"><h3>سجل العمل</h3><div class="metric">${db.assignments.length}</div></div><div class="card"><h3>الاستلاف والتسليف</h3><div class="metric">${db.loans.length}</div></div></div><h3>الحالة</h3><div class="grid">${db.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><p>${esc(d.status)}</p><span class="pill">${allHistory(d.id).length} فترات عمل</span></div>`).join('')}</div>`;}
function weekRows(w){return MISSIONS.map(m=>`<tr><td>${m.seq}</td><td>${m.day}</td><td><b>${m.name}</b></td><td>${m.id==='forest'?'Alpha: 17→23، 05→11، 11→17 / MO: 17→22، 07→12، 12→17':m.periods.map(p=>p.join('→')).join(' + ')}</td><td>${m.need}</td><td>${m.night?'نعم':'لا'}</td><td>${esc(m.note)}</td></tr>`).join('')}
function renderWeek(){const w=currentWeek();return `<h2>الجدول الأسبوعي</h2><div class="toolbar"><div class="field"><label>بداية الأسبوع</label><input type="date" id="weekDate" value="${w?.start||sundayOf(iso(new Date()))}"></div><button id="newWeek">إنشاء أسبوع</button></div>${w?`<div class="table-wrap"><table><thead><tr><th>#</th><th>اليوم</th><th>المهمة</th><th>الفترات</th><th>السواق</th><th>ليلي؟</th><th>التوضيح</th></tr></thead><tbody>${weekRows(w)}</tbody></table></div>`:'<div class="empty">أنشئ أسبوعًا أولًا.</div>'}`;}
function roleOptions(){return `<option value="alpha_pair">Alpha — بداية + نهاية</option><option value="alpha_middle">Alpha — الوسط</option><option value="mo_pair">MO — بداية + صباح</option><option value="mo_end">MO — النهاية</option>`}
function renderAssign(){const w=currentWeek();if(!w)return '<div class="empty">أنشئ أسبوعًا أولًا.</div>';return `<h2>التوزيع الفعلي</h2><div class="card"><div class="toolbar"><div class="field"><label>المهمة</label><select id="missionSel">${MISSIONS.map(m=>`<option value="${m.id}">${m.seq}. ${m.name}</option>`).join('')}</select></div><div class="field" id="forestTypeBox" style="display:none"><label>الغابة</label><select id="forestType"><option>Alpha</option><option>MO</option></select></div><div class="field" id="roleBox" style="display:none"><label>الدور</label><select id="forestRole">${roleOptions()}</select></div><div class="field"><label>السائق</label><select id="driverSel">${active().map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>سبب الاستثناء (اختياري)</label><input id="reason" placeholder="مثال: سائق مستعار"></div><button id="suggestBtn">اقتراح الدور</button><button id="recordBtn">تسجيل</button></div><div id="assignmentReason"></div></div><h3>توزيعات الأسبوع</h3>${renderWeekAssignments(w)}`;}
function renderWeekAssignments(w){const a=db.assignments.filter(x=>x.weekId===w.id).sort((x,y)=>new Date(x.start)-new Date(y.start));if(!a.length)return '<div class="empty">لا توجد توزيعات فعلية بعد.</div>';return `<div class="table-wrap"><table><thead><tr><th>السائق</th><th>اليوم/التاريخ</th><th>المهمة</th><th>الدور</th><th>الوقت</th><th>الراحة قبلها</th><th>استثناء</th></tr></thead><tbody>${a.map(x=>{const d=db.drivers.find(q=>q.id===x.driverId),m=mission(x.missionId),r=restBefore(x.driverId,x.start);return `<tr><td>${esc(d?.name)}</td><td>${fmt(x.start)}</td><td>${esc(m?.name||'الغابة')}</td><td>${esc(roleLabel(x.role))}</td><td>${fmt(x.start)} → ${fmt(x.end)}</td><td>${r?durationText(r.hours):'لا سجل سابق'}</td><td>${esc(x.reason||'—')}</td></tr>`}).join('')}</tbody></table></div>`}
function roleLabel(r){const map={alpha_pair:'Alpha: بداية + نهاية',alpha_middle:'Alpha: الوسط',mo_pair:'MO: بداية + صباح',mo_end:'MO: النهاية'};return map[r]||'—'}
function suggestUI(){const m=mission(document.getElementById('missionSel').value),w=currentWeek(),isF=m.id==='forest';let type=isF?document.getElementById('forestType').value:'',role=isF?document.getElementById('forestRole').value:'';let start=isF?forestPeriods(w,type,role)[0].start:periodForMission(m,w)[0].start;const cs=candidates(m.id,role,type,start);if(!cs.length)return;document.getElementById('driverSel').value=cs[0].d.id;document.getElementById('assignmentReason').innerHTML=`<div class="reason"><b>المقترح: ${esc(cs[0].d.name)}</b><br>${candidateExplain(cs[0],m,isF,role,type)}<hr>${cs.slice(0,4).map((c,i)=>`${i+1}. <b>${esc(c.d.name)}</b> — آخر نفس الدور: ${c.exact?fmt(c.exact.start):'لم يعمل من قبل'} — آخر المهمة: ${c.same?fmt(c.same.start):'لم يعمل'} — أدوار فائتة: ${c.missed}`).join('<br>')}</div>`;}
function candidateExplain(c,m,isF,role,type){const parts=[];if(c.missed)parts.push(`لديه ${c.missed} دور فائت مسجل في هذه المهمة`);parts.push(c.exact?`آخر مرة في نفس الدور: ${fmt(c.exact.start)}`:'لم يعمل هذا الدور من قبل');parts.push(c.same?`آخر مرة في المهمة: ${fmt(c.same.start)}`:'لم يعمل المهمة من قبل');if(c.rest)parts.push(`آخر راحة متصلة قبل هذه المهمة: ${durationText(c.rest.hours)} من ${fmt(c.rest.from)} إلى ${fmt(c.rest.to)}`);else parts.push('لا يوجد عمل سابق يمكن حساب الراحة منه');if(c.exchange)parts.push(`آخر استلاف/تسليف: ${c.exchange.type} بتاريخ ${fmt(c.exchange.date)}`);return parts.join('<br>')}
function recordCurrent(){const w=currentWeek();if(!w)return;const m=mission(document.getElementById('missionSel').value),id=Number(document.getElementById('driverSel').value),reason=document.getElementById('reason').value.trim();if(m.id==='forest'){recordForest(w,document.getElementById('forestType').value,document.getElementById('forestRole').value,id,reason)}else recordMission(m,w,id,reason);save();toast('تم تسجيل التوزيع الفعلي');}
function renderDrivers(){return `<h2>السواق والحالات</h2><div class="grid">${db.drivers.map(d=>`<div class="card"><h3>${esc(d.name)}</h3><div class="field"><label>الحالة</label><select data-status="${d.id}"><option ${d.status==='متاح'?'selected':''}>متاح</option><option ${d.status==='عطلة'?'selected':''}>عطلة</option><option ${d.status==='عجز طبي'?'selected':''}>عجز طبي</option><option ${d.status==='مستعار'?'selected':''}>مستعار</option><option ${d.status==='مسلف'?'selected':''}>مسلف</option></select></div><p>آخر عمل: ${lastOverall(d.id)?fmt(lastOverall(d.id).start):'لا يوجد'}</p><p>فترات العمل المسجلة: ${allHistory(d.id).length}</p></div>`).join('')}</div><h3>استثناء / استلاف / تسليف</h3><div class="card"><div class="toolbar"><div class="field"><label>السائق</label><select id="loanDriver">${db.drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>النوع</label><select id="loanType"><option value="استلف">استلف</option><option value="سلف">سلف</option></select></div><div class="field"><label>الفرقة الأخرى</label><input id="loanTeam"></div><div class="field"><label>المهمة</label><input id="loanMission"></div><div class="field"><label>البداية</label><input type="datetime-local" id="loanStart"></div><div class="field"><label>النهاية</label><input type="datetime-local" id="loanEnd"></div><div class="field"><label>السبب</label><input id="loanReason"></div><button id="loanBtn">تسجيل</button></div></div>`}
function renderHistory(){return `<h2>السجل والمقارنة</h2><div class="toolbar"><div class="field"><label>السائق</label><select id="historyDriver">${db.drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><button id="showHistory">عرض</button></div><div id="historyOut"></div>`}
function showHistory(){const id=Number(document.getElementById('historyDriver').value),{d,rows}=compareDriver(id);let html=`<h3>${esc(d.name)}</h3><div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>المهمة</th><th>الدور</th><th>العمل</th><th>الراحة قبل المهمة</th><th>السبب/الاستثناء</th></tr></thead><tbody>`;for(const x of rows){const a=x.a,m=mission(a.missionId);html+=`<tr><td>${fmt(a.start)}</td><td>${esc(m?.name||'الغابة')}</td><td>${esc(roleLabel(a.role))}</td><td>${fmt(a.start)} → ${fmt(a.end)}</td><td>${x.r?`${durationText(x.r.hours)}<br><span class="small">من ${fmt(x.r.from)} إلى ${fmt(x.r.to)}</span>`:'لا سجل سابق'}</td><td>${esc(a.reason||'—')}</td></tr>`}html+='</tbody></table></div><h3>الاستلاف والتسليف</h3>';const loans=db.loans.filter(x=>x.driverId===id);html+=loans.length?`<div class="table-wrap"><table><thead><tr><th>النوع</th><th>الفرقة</th><th>المهمة</th><th>الفترة</th><th>السبب</th></tr></thead><tbody>${loans.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.otherTeam)}</td><td>${esc(x.missionName)}</td><td>${esc(x.start||'')} → ${esc(x.end||'')}</td><td>${esc(x.reason||'')}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">لا يوجد سجل استلاف/تسليف.</p>';document.getElementById('historyOut').innerHTML=html;}
function renderFairness(){const w=currentWeek();if(!w)return '<div class="empty">أنشئ أسبوعًا أولًا.</div>';return `<h2>الدور القادم</h2><p class="muted">الاختيار يرجع إلى التاريخ الكامل: نفس الدور أولًا، ثم آخر مرة، ثم عدد مرات المهمة، مع عرض الراحة والاستثناءات. لا توجد نقاط مصطنعة.</p><div class="grid">${MISSIONS.map(m=>{const isF=m.id==='forest';const type=isF?'Alpha':'';const role=isF?'alpha_pair':'';const start=isF?forestPeriods(w,type,role)[0].start:periodForMission(m,w)[0].start;const cs=candidates(m.id,role,type,start);const c=cs[0];return `<div class="card"><h3>${m.seq}. ${m.name}</h3><p>${c?`المقترح: <b>${esc(c.d.name)}</b>`:'لا يوجد متاح'}</p>${c?`<p class="small">${c.exact?'آخر نفس الدور: '+fmt(c.exact.start):'لم يعمل الدور من قبل'}<br>آخر المهمة: ${c.same?fmt(c.same.start):'لم يعمل'}<br>الراحة قبلها: ${c.rest?durationText(c.rest.hours):'لا سجل سابق'}</p>`:''}</div>`}).join('')}</div>`}
function bind(){document.querySelectorAll('[data-status]').forEach(x=>x.onchange=()=>markStatus(Number(x.dataset.status),x.value));const nw=document.getElementById('newWeek');if(nw)nw.onclick=()=>createWeek(document.getElementById('weekDate').value);const ab=document.getElementById('suggestBtn');if(ab)ab.onclick=suggestUI;const rb=document.getElementById('recordBtn');if(rb)rb.onclick=recordCurrent;const ms=document.getElementById('missionSel');if(ms)ms.onchange=()=>{const f=ms.value==='forest';document.getElementById('forestTypeBox').style.display=f?'flex':'none';document.getElementById('roleBox').style.display=f?'flex':'none'};const lb=document.getElementById('loanBtn');if(lb)lb.onclick=()=>logLoan(Number(document.getElementById('loanDriver').value),document.getElementById('loanType').value,document.getElementById('loanTeam').value,document.getElementById('loanMission').value,document.getElementById('loanStart').value,document.getElementById('loanEnd').value,document.getElementById('loanReason').value);const hb=document.getElementById('showHistory');if(hb)hb.onclick=showHistory;}
function render(){const activeTab=document.querySelector('.tabs button.active')?.dataset.tab||'dashboard';document.querySelectorAll('.tab').forEach(s=>s.classList.remove('active'));const target=document.getElementById(activeTab);if(target){target.classList.add('active');target.innerHTML=activeTab==='dashboard'?renderDashboard():activeTab==='week'?renderWeek():activeTab==='assign'?renderAssign():activeTab==='drivers'?renderDrivers():activeTab==='history'?renderHistory():renderFairness();}document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});bind();}
function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sowa9-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.drivers||!x.assignments)throw Error();db=Object.assign(fresh(),x);save();toast('تم الاستيراد')}catch(e){toast('ملف غير صالح')}};r.readAsText(file)}
document.getElementById('exportBtn')?.addEventListener('click',exportData);document.getElementById('importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click());document.getElementById('importFile')?.addEventListener('change',e=>e.target.files[0]&&importData(e.target.files[0]));render();