/* Sowa9 v5 — historical fairness engine, Arabic RTL, local-first */
'use strict';
const KEY='sowa9.v5';
const DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const DRIVERS=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const INITIAL_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز طبي',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',seq:1,name:'دنيا برك',day:'الأحد',need:2,night:false,periods:[['12:00','22:00']],kind:'نقل مشترك',note:'نقل مشترك.'},
{id:'garden',seq:2,name:'غاردن سيتي',day:'الأحد',need:2,night:true,periods:[['17:00','00:00']],kind:'نقل مشترك',note:'تمتد إلى الليل؛ تُحسب ليلية.'},
{id:'bahja',seq:3,name:'البحر — بهجة',day:'الثلاثاء',need:1,night:false,periods:[['09:00','22:00']],kind:'خارجي متعب',note:'حرارة؛ بهجة أصعب. لا تُحسب ليلية.'},
{id:'club',seq:4,name:'البحر — كلوب',day:'الثلاثاء',need:3,night:false,periods:[['12:00','22:00']],kind:'خارجي متعب',note:'حرارة. لا تُحسب ليلية.'},
{id:'bondage',seq:5,name:'بونداج زرالدة',day:'الأربعاء',need:2,night:false,periods:[['04:30','10:00']],kind:'نقل مشترك',note:'نقل مشترك.'},
{id:'guard',seq:6,name:'حراسة',day:'الأربعاء',need:1,night:true,periods:[['17:00','00:00']],kind:'داخلي مريح',note:'داخلي ومريح، لكنه يُحسب عملًا ليليًا.'},
{id:'raids',seq:7,name:'مداهمات',day:'الخميس',need:2,night:true,periods:[['19:30','05:00']],kind:'خارجي ليلي',note:'عمل خارجي ليلي.'},
{id:'delivery',seq:8,name:'توصيل',day:'الخميس',need:1,night:false,periods:[['20:00','21:30'],['06:30','08:00']],kind:'فترتان',note:'فترتان منفصلتان.'},
{id:'barajat',seq:9,name:'براجات',day:'الجمعة',need:1,night:false,periods:[['06:00','12:00']],kind:'داخلي مريح',note:'داخلي ومريح، ليس عملًا ليليًا.'},
{id:'forest',seq:10,name:'الغابة',day:'الجمعة',need:4,night:false,periods:[],kind:'نظام خاص',note:'24 ساعة؛ Alpha وMO.'}
];
const FOREST={
 Alpha:[
  {id:'alpha_start_end',label:'Alpha — بداية 17→23 ثم عودة 11→17',periods:[['17:00','23:00'],['11:00','17:00']]},
  {id:'alpha_middle',label:'Alpha — الوسط 05→11',periods:[['05:00','11:00']]}
 ],
 MO:[
  {id:'mo_start_morning',label:'MO — بداية 17→22 ثم عودة 07→12',periods:[['17:00','22:00'],['07:00','12:00']]},
  {id:'mo_end',label:'MO — النهاية 12→17',periods:[['12:00','17:00']]}
 ]
};
function fresh(){return {version:5,drivers:DRIVERS.map((name,i)=>({id:i+1,name,status:INITIAL_STATUS[name]})),weeks:[],assignments:[],loans:[],missed:[],events:[]};}
let db=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===5)return x;}catch(e){} return fresh();}
function save(msg){localStorage.setItem(KEY,JSON.stringify(db));render();if(msg)toast(msg);}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random();}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window._t);window._t=setTimeout(()=>e.classList.remove('show'),2200);}
function parseDate(v){return new Date(v);}
function dateOnly(v){return new Date(v+'T12:00:00');}
function iso(d){return d.toISOString().slice(0,10);}
function sunday(v){const d=dateOnly(v);d.setDate(d.getDate()-d.getDay());return iso(d);}
function dayDate(week,day){const d=dateOnly(week);d.setDate(d.getDate()+DAYS.indexOf(day));return iso(d);}
function makeDT(date,time,overnight=false){const d=new Date(date+'T'+time+':00');if(overnight)d.setDate(d.getDate()+1);return d;}
function fmt(v){return parseDate(v).toLocaleString('ar-DZ',{dateStyle:'short',timeStyle:'short'});}
function dur(a,b){return Math.max(0,(parseDate(b)-parseDate(a))/3600000);}
function durText(h){const mins=Math.round(h*60),days=Math.floor(mins/1440),r=mins%1440,hh=Math.floor(r/60),mm=r%60;return (days?days+' يوم ':'')+hh+' ساعة '+mm+' دقيقة';}
function mission(id){return MISSIONS.find(m=>m.id===id);}
function active(){return db.drivers.filter(d=>d.status==='متاح'||d.status==='مستعار');}
function week(){return db.weeks[0]||null;}
function allHistory(id){return db.assignments.filter(a=>a.driverId===id&&!a.planned).sort((a,b)=>parseDate(a.start)-parseDate(b.start));}
function lastOverall(id,before){let x=allHistory(id).filter(a=>!before||parseDate(a.start)<parseDate(before));return x.at(-1)||null;}
function lastMission(id,mid,before){let x=allHistory(id).filter(a=>a.missionId===mid&&(!before||parseDate(a.start)<parseDate(before)));return x.at(-1)||null;}
function lastRole(id,mid,role,type,before){let x=allHistory(id).filter(a=>a.missionId===mid&&(!role||a.role===role)&&(!type||a.forestType===type)&&(!before||parseDate(a.start)<parseDate(before)));return x.at(-1)||null;}
function lastExchange(id){return db.loans.filter(x=>x.driverId===id).sort((a,b)=>parseDate(b.date)-parseDate(a.date))[0]||null;}
function missedFor(id,mid,role,type){return db.missed.filter(x=>x.driverId===id&&x.missionId===mid&&(!role||x.role===role)&&(!type||x.forestType===type)&&!x.resolved);}
function restBefore(id,start){const p=lastOverall(id,start);return p?{previous:p,from:p.end,to:start,hours:dur(p.end,start)}:null;}
function periodsFor(m,w){const base=dayDate(w.start,m.day);return m.periods.map((p,i)=>{const overnight=p[1]<'12:00'&&p[0]>='12:00';return {start:makeDT(base,p[0]),end:makeDT(base,p[1],overnight)};});}
function forestPeriods(w,type,roleId){const base=dayDate(w.start,'الجمعة'),role=FOREST[type].find(r=>r.id===roleId);return role.periods.map((p,i)=>{let s=makeDT(base,p[0]),e=makeDT(base,p[1],p[1]<'12:00'&&p[0]>='12:00');if(i>0||p[0]<'17:00'){s.setDate(s.getDate()+1);e.setDate(e.getDate()+1);}return {start:s,end:e};});}
function candidates(mid,{role='',type='',start=null}={}){const when=start||new Date().toISOString();return active().map(d=>{
 const exact=lastRole(d.id,mid,role,type,when), same=lastMission(d.id,mid,when), overall=lastOverall(d.id,when), rest=restBefore(d.id,when), missed=missedFor(d.id,mid,role,type), exchange=lastExchange(d.id);
 return {d,exact,same,overall,rest,missed,exchange,count:db.assignments.filter(a=>a.driverId===d.id&&a.missionId===mid&&!a.planned).length};
}).sort((a,b)=>{
 if(a.missed.length!==b.missed.length)return b.missed.length-a.missed.length;
 if(!a.exact&&!b.exact){if(!a.same&&!b.same)return a.d.id-b.d.id;if(!a.same)return -1;if(!b.same)return 1;}
 if(!a.exact)return -1;if(!b.exact)return 1;
 const t=parseDate(a.exact.start)-parseDate(b.exact.start);if(t)return t;
 if(a.count!==b.count)return a.count-b.count;
 const ar=a.rest?.hours??Infinity,br=b.rest?.hours??Infinity;if(ar!==br)return br-ar;
 const ao=a.overall?parseDate(a.overall.start).getTime():-Infinity,bo=b.overall?parseDate(b.overall.start).getTime():-Infinity;return ao-bo;
});}
function explanation(c,mid){const m=mission(mid),p=[];if(c.missed.length)p.push(`له ${c.missed.length} دور فائت غير محلول في هذه المهمة`);if(!c.exact)p.push(c.same?'لم يأخذ هذا الدور المحدد سابقًا، رغم أنه عمل المهمة':'لم يعمل هذه المهمة من قبل');else p.push(`آخر مرة أخذ هذا الدور: ${fmt(c.exact.start)}`);if(c.rest)p.push(`آخر عمل انتهى ${fmt(c.rest.previous.end)} ثم الفراغ حتى ${fmt(c.rest.to)} = ${durText(c.rest.hours)}`);else p.push('لا يوجد عمل سابق مسجل قبل هذه المهمة');if(c.exchange)p.push(`آخر استلاف/تسليف: ${c.exchange.type} — ${c.exchange.missionName||'—'} (${fmt(c.exchange.date)})`);return p.join(' • ');}
function addAssignment(o){db.assignments.push({id:uid(),planned:false,createdAt:new Date().toISOString(),...o});}
function assignMission(mid,driverId,w,reason='',replacement=false){const m=mission(mid),ps=periodsFor(m,w),link=ps.length>1?uid():null;ps.forEach((p,i)=>addAssignment({weekId:w.id,missionId:mid,driverId,start:p.start.toISOString(),end:p.end.toISOString(),part:i+1,linkedId:link,replacement,reason}));}
function assignForest(type,roleId,driverId,w,reason=''){const ps=forestPeriods(w,type,roleId),link=ps.length>1?uid():null;ps.forEach((p,i)=>addAssignment({weekId:w.id,missionId:'forest',driverId,start:p.start.toISOString(),end:p.end.toISOString(),part:i+1,linkedId:link,role:roleId,forestType:type,replacement:false,reason}));}
function createWeek(start){start=sunday(start);if(db.weeks.some(w=>w.start===start)){toast('الأسبوع موجود');return;}db.weeks.unshift({id:uid(),start,createdAt:new Date().toISOString()});save('تم إنشاء الأسبوع');}
function logMissed(w,mid,driverId,role,type,reason){if(!db.missed.some(x=>x.weekId===w.id&&x.missionId===mid&&x.driverId===driverId&&x.role===role&&!x.resolved))db.missed.push({id:uid(),weekId:w.id,missionId:mid,driverId,role,type,reason,resolved:false,date:new Date().toISOString()});}
function logLoan(driverId,type,otherTeam,missionName,start,end,reason){db.loans.push({id:uid(),driverId,type,otherTeam,missionName,start,end,date:new Date().toISOString(),reason});save('تم تسجيل الاستلاف/التسليف');}
function setStatus(id,status){const d=db.drivers.find(x=>x.id===id);if(!d)return;const old=d.status;d.status=status;db.events.push({id:uid(),type:'status',driverId:id,old,status,date:new Date().toISOString()});save(`تم تغيير حالة ${d.name}`);}
function resolveMissed(id){const x=db.missed.find(m=>m.id===id);if(x){x.resolved=true;x.resolvedAt=new Date().toISOString();save('تم تسجيل استرجاع الدور');}}
function exportDB(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sowa9-backup.json';a.click();URL.revokeObjectURL(a.href);}
function importDB(file){const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x||!x.drivers||!x.assignments)throw Error();db=x;localStorage.setItem(KEY,JSON.stringify(db));render();toast('تم الاستيراد');}catch(e){toast('ملف غير صالح');}};r.readAsText(file);}
function renderDashboard(){const w=week();return `<h2>لوحة القيادة</h2><div class="grid"><div class="card"><small>الأسبوع الحالي</small><strong>${w?esc(w.start):'—'}</strong><span>الحساب يعاد أسبوعيًا، والسجل لا يُحذف.</span></div><div class="card"><small>السواق المتاحون</small><strong>${active().length}</strong></div><div class="card"><small>فترات العمل المسجلة</small><strong>${db.assignments.filter(a=>!a.planned).length}</strong></div><div class="card"><small>استلاف/تسليف</small><strong>${db.loans.length}</strong></div></div><h3>حالة السواق</h3><div class="driver-grid">${db.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><span class="pill">${esc(d.status)}</span><small>${allHistory(d.id).length} فترات عمل</small></div>`).join('')}</div>`;}
function renderWeek(){const w=week();return `<h2>الأسبوع والمهام</h2><div class="toolbar"><label>بداية الأسبوع <input id="weekDate" type="date" value="${w?.start||sunday(iso(new Date()))}"></label><button id="newWeek">إنشاء أسبوع</button></div>${w?`<div class="table-wrap"><table><thead><tr><th>#</th><th>اليوم</th><th>المهمة</th><th>وقت العمل</th><th>عدد</th><th>ليلية</th><th>الوصف</th></tr></thead><tbody>${MISSIONS.map(m=>`<tr><td>${m.seq}</td><td>${m.day}</td><td>${m.name}</td><td>${m.id==='forest'?'Alpha: 17→23 + 05→11 + 11→17<br>MO: 17→22 + 07→12 + 12→17':m.periods.map(p=>p.join(' → ')).join('<br>')}</td><td>${m.need}</td><td>${m.night?'نعم':'لا'}</td><td>${m.note}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">أنشئ أسبوعًا أولًا.</div>'}`;}
function renderAssign(){const w=week();if(!w)return '<div class="empty">أنشئ أسبوعًا أولًا.</div>';return `<h2>التوزيع الفعلي</h2><div class="card"><div class="toolbar"><label>المهمة <select id="missionSel">${MISSIONS.map(m=>`<option value="${m.id}">${m.seq}. ${m.name}</option>`).join('')}</select></label><label id="forestBox" hidden>نوع الغابة <select id="forestType"><option value="Alpha">Alpha</option><option value="MO">MO</option></select></label><label id="roleBox" hidden>الدور <select id="forestRole"></select></label><button id="suggestBtn">اقترح حسب التاريخ</button></div><div id="suggestions"></div></div><div class="card"><h3>تسجيل سائق فعلي</h3><p class="muted">يمكن للقائد اختيار السائق، وإذا كان استثناءً سجّل السبب. السجل الفعلي هو الذي يدخل في الحساب.</p><div class="toolbar"><label>السائق <select id="actualDriver">${db.drivers.map(d=>`<option value="${d.id}">${d.name} — ${d.status}</option>`).join('')}</select></label><label>استثناء/سبب <input id="assignReason" placeholder="مثال: استلاف من فرقة أخرى"></label><button id="saveActual">تسجيل</button></div></div>`;}
function renderDrivers(){return `<h2>السواق والحالات</h2><div class="driver-grid">${db.drivers.map(d=>`<div class="card"><h3>${esc(d.name)}</h3><p>الحالة: <b>${esc(d.status)}</b></p><div class="toolbar"><select data-status="${d.id}"><option>متاح</option><option>عطلة</option><option>عجز طبي</option><option>مستعار</option><option>مسلف</option></select><button data-save-status="${d.id}">حفظ</button></div><small>عمل مسجل: ${allHistory(d.id).length}</small></div>`).join('')}</div><div class="card"><h3>الاستلاف والتسليف</h3><div class="toolbar"><select id="loanDriver">${db.drivers.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select><select id="loanType"><option value="استلاف">استلاف</option><option value="تسليف">تسليف</option></select><input id="loanTeam" placeholder="الفرقة الأخرى"><input id="loanMission" placeholder="المهمة"><input id="loanStart" type="datetime-local"><input id="loanEnd" type="datetime-local"><input id="loanReason" placeholder="السبب"><button id="saveLoan">تسجيل</button></div></div>`;}
function renderHistory(){const rows=[...db.assignments].filter(a=>!a.planned).sort((a,b)=>parseDate(a.start)-parseDate(b.start));return `<h2>السجل والمقارنة</h2><div class="card"><label>السائق <select id="historyDriver"><option value="all">الكل</option>${db.drivers.map(d=>`<option value="${d.id}">${d.name}</option>`).join('')}</select></label><div id="historyTable"></div></div><div class="card"><h3>الأدوار الفائتة</h3>${db.missed.length?`<div class="table-wrap"><table><thead><tr><th>السائق</th><th>المهمة</th><th>التاريخ</th><th>السبب</th><th>الحالة</th><th></th></tr></thead><tbody>${db.missed.map(x=>`<tr><td>${db.drivers.find(d=>d.id===x.driverId)?.name||'—'}</td><td>${mission(x.missionId)?.name||'الغابة'}</td><td>${fmt(x.date)}</td><td>${esc(x.reason)}</td><td>${x.resolved?'مسترجع':'غير محلول'}</td><td>${x.resolved?'':`<button data-resolve="${x.id}">تسجيل الاسترجاع</button>`}</td></tr>`).join('')}</tbody></table></div>`:'لا توجد أدوار فائتة.'}</div>`;}
function buildHistory(id){const ds=id==='all'?db.drivers:db.drivers.filter(d=>String(d.id)===String(id));return ds.map(d=>{const h=allHistory(d.id);return `<div class="driver-history"><h3>${d.name}</h3>${h.length?`<div class="table-wrap"><table><thead><tr><th>المهمة</th><th>اليوم/البداية</th><th>النهاية</th><th>الراحة قبلها</th><th>الدور/الغابة</th><th>استثناء</th></tr></thead><tbody>${h.map(a=>{const r=restBefore(d.id,a.start);const m=mission(a.missionId);return `<tr><td>${m?.name||'الغابة'}${a.forestType?' — '+a.forestType:''}</td><td>${fmt(a.start)}</td><td>${fmt(a.end)}</td><td>${r?`من ${fmt(r.from)} إلى ${fmt(r.to)}<br><b>${durText(r.hours)}</b>`:'لا يوجد سجل سابق'}</td><td>${a.role?esc(a.role):'—'}</td><td>${esc(a.reason||'—')}</td></tr>`}).join('')}</tbody></table></div>`:'لا يوجد عمل مسجل.'}</div>`;}).join('');}
function renderFairness(){const w=week();return `<h2>الدور القادم — قرار قابل للمراجعة</h2>${w?`<div class="card"><div class="toolbar"><label>المهمة <select id="fairMission">${MISSIONS.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select></label><label id="fairForest" hidden>الغابة <select id="fairType"><option>Alpha</option><option>MO</option></select></label><label id="fairRole" hidden>الدور <select id="fairRoleSel"></select></label><button id="fairBtn">احسب الدور</button></div><div id="fairResult"></div></div>`:'<div class="empty">أنشئ أسبوعًا أولًا.</div>'}<div class="card"><h3>قاعدة القرار</h3><p>لا توجد نقاط اصطناعية. النظام يرجع إلى السجل الفعلي: آخر دور في المهمة، الدور الفائت بسبب عدم التوفر، آخر عمل، الراحة المتصلة بالتاريخ والساعة، والاستلاف/التسليف. عند التعادل يُستخدم الأقدم ثم الأقل مرات.</p></div>`;}
function render(){document.querySelector('#dashboard').innerHTML=renderDashboard();document.querySelector('#week').innerHTML=renderWeek();document.querySelector('#assign').innerHTML=renderAssign();document.querySelector('#drivers').innerHTML=renderDrivers();document.querySelector('#history').innerHTML=renderHistory();document.querySelector('#fairness').innerHTML=renderFairness();bind();}
function showTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));if(id==='history')updateHistory();}
function fillForestRoles(select,type){select.innerHTML=FOREST[type].map(r=>`<option value="${r.id}">${r.label}</option>`).join('');}
function selectedSpec(prefix){const mid=document.getElementById(prefix+'Mission')?.value||document.getElementById('missionSel')?.value;let type='',role='';if(mid==='forest'){type=document.getElementById(prefix+'Type')?.value||document.getElementById('forestType')?.value;role=document.getElementById(prefix+'RoleSel')?.value||document.getElementById('forestRole')?.value;}return {mid,type,role};}
function updateSuggestions(){const w=week(),mid=document.getElementById('missionSel').value,type=mid==='forest'?document.getElementById('forestType').value:'',role=mid==='forest'?document.getElementById('forestRole').value:'',start=mid==='forest'?forestPeriods(w,type,role)[0].start:periodsFor(mission(mid),w)[0].start;const cs=candidates(mid,{role,type,start:start.toISOString()});document.getElementById('suggestions').innerHTML=`<h3>الترتيب التاريخي للمرشحين</h3><div class="candidate-list">${cs.map((c,i)=>`<div class="candidate ${i===0?'best':''}"><b>#${i+1} ${c.d.name}</b><span>آخر هذه المهمة: ${c.exact?fmt(c.exact.start):'لم يعملها'}</span><span>مرات المهمة: ${c.count}</span><span>الراحة قبلها: ${c.rest?durText(c.rest.hours):'لا سجل سابق'}</span><span>${explanation(c,mid)}</span></div>`).join('')}</div>`;document.getElementById('actualDriver').value=cs[0]?.d.id||'';}
function updateFair(){const w=week(),mid=document.getElementById('fairMission').value,type=mid==='forest'?document.getElementById('fairType').value:'',role=mid==='forest'?document.getElementById('fairRoleSel').value:'',start=mid==='forest'?forestPeriods(w,type,role)[0].start:periodsFor(mission(mid),w)[0].start,cs=candidates(mid,{role,type,start:start.toISOString()});const best=cs[0];document.getElementById('fairResult').innerHTML=best?`<div class="best-result"><h3>المستحق حاليًا: ${best.d.name}</h3><p>${explanation(best,mid)}</p><div class="table-wrap"><table><thead><tr><th>السائق</th><th>آخر نفس الدور</th><th>آخر المهمة</th><th>الراحة</th><th>الأدوار الفائتة</th><th>آخر استلاف/تسليف</th></tr></thead><tbody>${cs.map(c=>`<tr><td>${c.d.name}</td><td>${c.exact?fmt(c.exact.start):'لم يعمل'}</td><td>${c.same?fmt(c.same.start):'لم يعمل'}</td><td>${c.rest?durText(c.rest.hours):'—'}</td><td>${c.missed.length}</td><td>${c.exchange?c.exchange.type+' — '+esc(c.exchange.missionName):'—'}</td></tr>`).join('')}</tbody></table></div></div>`:'لا يوجد سائق متاح.';}
function updateHistory(){const e=document.getElementById('historyTable');if(e)e.innerHTML=buildHistory(document.getElementById('historyDriver')?.value||'all');}
function bind(){
 document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
 document.getElementById('exportBtn')?.addEventListener('click',exportDB);document.getElementById('importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click());document.getElementById('importFile')?.addEventListener('change',e=>e.target.files[0]&&importDB(e.target.files[0]));
 document.getElementById('newWeek')?.addEventListener('click',()=>createWeek(document.getElementById('weekDate').value));
 const ms=document.getElementById('missionSel');if(ms)ms.onchange=()=>{const forest=ms.value==='forest';document.getElementById('forestBox').hidden=!forest;document.getElementById('roleBox').hidden=!forest;if(forest)fillForestRoles(document.getElementById('forestRole'),document.getElementById('forestType').value);};document.getElementById('forestType')?.addEventListener('change',()=>fillForestRoles(document.getElementById('forestRole'),document.getElementById('forestType').value));document.getElementById('suggestBtn')?.addEventListener('click',updateSuggestions);document.getElementById('saveActual')?.addEventListener('click',()=>{const w=week(),mid=ms.value,did=+document.getElementById('actualDriver').value,reason=document.getElementById('assignReason').value,type=mid==='forest'?document.getElementById('forestType').value:'',role=mid==='forest'?document.getElementById('forestRole').value:'';if(mid==='forest')assignForest(type,role,did,w,reason);else assignMission(mid,did,w,reason);save('تم تسجيل العمل الفعلي');});
 document.querySelectorAll('[data-save-status]').forEach(b=>b.onclick=()=>setStatus(+b.dataset.saveStatus,b.parentElement.querySelector('select').value));
 document.getElementById('saveLoan')?.addEventListener('click',()=>logLoan(+loanDriver.value,loanType.value,loanTeam.value,loanMission.value,loanStart.value,loanEnd.value,loanReason.value));
 document.getElementById('historyDriver')?.addEventListener('change',updateHistory);document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>resolveMissed(b.dataset.resolve));
 const fm=document.getElementById('fairMission');if(fm)fm.onchange=()=>{const f=fm.value==='forest';document.getElementById('fairForest').hidden=!f;document.getElementById('fairRole').hidden=!f;if(f)fillForestRoles(document.getElementById('fairRoleSel'),document.getElementById('fairType').value);};document.getElementById('fairType')?.addEventListener('change',()=>fillForestRoles(document.getElementById('fairRoleSel'),document.getElementById('fairType').value));document.getElementById('fairBtn')?.addEventListener('click',updateFair);
}
showTab('dashboard');render();
