/* Sowa9 v6 — production local-first scheduler
 * Principles: historical fairness, immutable history, explicit exceptions,
 * deterministic proposals, forest-specific scheduling, role-based writes.
 */
'use strict';
const KEY='sowa9.v6';
const DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const STATUSES=['متاح','عطلة','عجز','مستعار','مسلف'];
const ROLES=['ADMIN','LEADER','VIEWER'];
const MIN_REST_DEFAULT=8;
const DRIVERS0=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const INITIAL_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',seq:1,name:'دنيا برك',day:'الأحد',need:2,periods:[['12:00','22:00']],kind:'نقل مشترك'},
{id:'garden',seq:2,name:'غاردن سيتي',day:'الأحد',need:2,periods:[['17:00','00:00']],kind:'نقل مشترك'},
{id:'bahja',seq:3,name:'البحر — بهجة',day:'الثلاثاء',need:1,periods:[['09:00','22:00']],kind:'خارجي متعب'},
{id:'club',seq:4,name:'البحر — كلوب',day:'الثلاثاء',need:3,periods:[['12:00','22:00']],kind:'خارجي متعب'},
{id:'bondage',seq:5,name:'بونداج زرالدة',day:'الأربعاء',need:2,periods:[['04:30','10:00']],kind:'نقل مشترك'},
{id:'guard',seq:6,name:'حراسة',day:'الأربعاء',need:1,periods:[['17:00','00:00']],kind:'داخلي مريح'},
{id:'raids',seq:7,name:'مداهمات',day:'الخميس',need:2,periods:[['19:30','05:00']],kind:'خارجي ليلي'},
{id:'delivery',seq:8,name:'توصيل',day:'الخميس',need:1,periods:[['20:00','21:30'],['06:30','08:00']],kind:'فترتان'},
{id:'barajat',seq:9,name:'براجات',day:'الجمعة',need:1,periods:[['06:00','12:00']],kind:'داخلي مريح'},
{id:'forest',seq:10,name:'الغابة',day:'الجمعة',need:4,periods:[],kind:'نظام خاص'}
];
const FOREST={
Alpha:[{id:'alpha_start_end',label:'Alpha — بداية 17→23 + عودة 11→17',periods:[['17:00','23:00'],['11:00','17:00']]},{id:'alpha_middle',label:'Alpha — الوسط 05→11',periods:[['05:00','11:00']]}],
MO:[{id:'mo_start_morning',label:'MO — بداية 17→22 + عودة 07→12',periods:[['17:00','22:00'],['07:00','12:00']]},{id:'mo_end',label:'MO — النهاية 12→17',periods:[['12:00','17:00']]}]
};
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2)}
function now(){return new Date().toISOString()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function dt(v){return new Date(v)}
function iso(v){return new Date(v).toISOString().slice(0,10)}
function sunday(v){const d=new Date((v||iso(new Date()))+'T12:00:00');d.setDate(d.getDate()-d.getDay());return iso(d)}
function dayDate(w,day){const d=new Date(w+'T12:00:00');d.setDate(d.getDate()+DAYS.indexOf(day));return iso(d)}
function makeDT(date,time,overnight=false){const d=new Date(date+'T'+time+':00');if(overnight)d.setDate(d.getDate()+1);return d}
function hours(a,b){return Math.max(0,(dt(b)-dt(a))/36e5)}
function fmt(v){return v?dt(v).toLocaleString('ar-DZ',{dateStyle:'short',timeStyle:'short'}):'—'}
function mission(id){return MISSIONS.find(x=>x.id===id)}
function driver(id){return state.drivers.find(x=>x.id===id)}
function dname(id){return driver(id)?.name||'—'}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===6)return x}catch(e){}return fresh()}
function fresh(){return {version:6,settings:{minRest:MIN_REST_DEFAULT,returnPolicy:'RECLAIM'},users:[{id:'u-admin',name:'المدير',role:'ADMIN'}],teams:[{id:'team-main',name:'الفرقة الأساسية'}],drivers:DRIVERS0.map((name,i)=>({id:'d'+(i+1),name,status:INITIAL_STATUS[name]})),weeks:[],assignments:[],missed:[],loans:[],events:[],decisions:[]}}
let state=load();
function persist(msg){localStorage.setItem(KEY,JSON.stringify(state));render();if(msg)toast(msg)}
function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>e.classList.remove('show'),2400)}
function currentUser(){return state.users.find(u=>u.id===sessionStorage.getItem('sowa9.user'))||state.users[0]}
function requireRole(...roles){const u=currentUser();if(!u||!roles.includes(u.role))throw Error('صلاحية غير كافية: يتطلب '+roles.join(' أو '));return u}
function canWrite(){return ['ADMIN','LEADER'].includes(currentUser()?.role)}
function audit(entity,id,action,from,to,reason=''){state.events.push({id:uid(),ts:now(),entity,entityId:id,action,from,to,reason,userId:currentUser()?.id||''})}
function getWeek(){return state.weeks.slice().sort((a,b)=>b.start.localeCompare(a.start))[0]||null}
function ensureCurrentWeek(){const s=sunday(iso(new Date()));let w=state.weeks.find(x=>x.start===s);if(!w){w={id:uid(),start:s,createdAt:now()};state.weeks.unshift(w);localStorage.setItem(KEY,JSON.stringify(state))}return w}
function periodsFor(m,w){const base=dayDate(w.start,m.day);return m.periods.map(p=>{const overnight=p[1]<'12:00'&&p[0]>='12:00';return {start:makeDT(base,p[0]),end:makeDT(base,p[1],overnight)}})}
function forestPeriods(w,type,roleId){const role=FOREST[type]?.find(r=>r.id===roleId);if(!role)throw Error('دور غابة غير معروف');const base=dayDate(w.start,'الجمعة');return role.periods.map((p,i)=>{let s=makeDT(base,p[0]),e=makeDT(base,p[1],p[1]<'12:00'&&p[0]>='12:00');if(i>0||p[0]<'17:00'){s.setDate(s.getDate()+1);e.setDate(e.getDate()+1)}return {start:s,end:e}})}
function history(id,before){return state.assignments.filter(a=>a.actual_driver_id===id&&a.status==='CONFIRMED'&&(!before||a.start_datetime<before)).sort((a,b)=>a.start_datetime.localeCompare(b.start_datetime))}
function lastOverall(id,before){return history(id,before).at(-1)||null}
function lastMission(id,mid,before){return history(id,before).filter(a=>a.mission_id===mid).at(-1)||null}
function lastRole(id,mid,slot,type,before){return history(id,before).filter(a=>a.mission_id===mid&&(!slot||a.forest_slot===slot)&&(!type||a.forest_type===type)).at(-1)||null}
function overlaps(id,start,end,excludeId){return history(id).filter(a=>a.id!==excludeId&&a.start_datetime<end.toISOString()&&a.end_datetime>start.toISOString())}
function restBefore(id,start){const p=lastOverall(id,start.toISOString());return p?{from:p.end_datetime,to:start.toISOString(),hours:hours(p.end_datetime,start.toISOString()),previous:p}:null}
function missedOpen(id,mid,slot,type){return state.missed.filter(x=>x.driver_id===id&&x.mission_id===mid&&(!slot||x.slot===slot)&&(!type||x.forest_type===type)&&!x.resolved).sort((a,b)=>a.date.localeCompare(b.date))}
function eligible(d){return d.status==='متاح'||d.status==='مستعار'}
function propose(entry,slotNo,excludeIds=[],slot=null){
 const m=mission(entry.mission_id),inst=entry.instances, start=inst[0].start,end=inst.at(-1).end;
 const rows=state.drivers.map(d=>{const ex=lastRole(d.id,m.id,slot,null,start.toISOString()),same=lastMission(d.id,m.id,start.toISOString()),overall=lastOverall(d.id,start.toISOString()),rb=restBefore(d.id,start),miss=missedOpen(d.id,m.id,slot,null),conf=overlaps(d.id,start,end),excluded=excludeIds.includes(d.id);return {d,ex,same,overall,rb,miss,conf,excluded,eligible:eligible(d)&&!excluded}});
 const rank=(a,b)=>{const ar=a.miss.some(x=>x.return_policy==='RECLAIM'),br=b.miss.some(x=>x.return_policy==='RECLAIM');if(ar!==br)return ar?-1:1;if(ar&&br){const ad=a.miss.find(x=>x.return_policy==='RECLAIM').date,bd=b.miss.find(x=>x.return_policy==='RECLAIM').date;if(ad!==bd)return ad.localeCompare(bd)}const ax=a.ex?.start_datetime||'9999',bx=b.ex?.start_datetime||'9999';if(ax!==bx)return ax.localeCompare(bx);const ac=a.same?1:0,bc=b.same?1:0;if(ac!==bc)return ac-bc;const ah=a.overall?.start_datetime||'',bh=b.overall?.start_datetime||'';return ah.localeCompare(bh)};
 const dueRank=rows.slice().sort(rank),dueRow=dueRank[0]||null,recommended=dueRank.find(x=>x.eligible&&!x.conf.length)||dueRank.find(x=>x.eligible)||null;
 const view=rows.slice().sort((a,b)=>{if(a.eligible!==b.eligible)return a.eligible?-1:1;if(a.conf.length!==b.conf.length)return a.conf.length-b.conf.length;return dueRank.indexOf(a)-dueRank.indexOf(b)});
 view.forEach(r=>r.explain=explain(r,m.id));
 return {mission:m,rows:view,dueRank,dueRow,recommended};
}
function explain(r,mid){const p=[];if(r.ex?.start_datetime)p.push('آخر مرة في الدور: '+fmt(r.ex.start_datetime));else if(r.same)p.push('عمل المهمة سابقًا، لكن ليس هذا الدور المحدد');else p.push('لم يعمل المهمة من قبل');if(r.miss.length)p.push('له '+r.miss.length+' دور فائت غير مسوّى'+(r.miss.some(x=>x.return_policy==='RECLAIM')?' — استرداد أولوية':' — عودة طبيعية'));if(r.rb)p.push('الراحة قبل المهمة: '+r.rb.hours.toFixed(1)+' ساعة');else p.push('لا يوجد عمل سابق مسجل قبلها');if(r.conf.length)p.push('تعارض مع '+r.conf.length+' فترة');if(r.excluded)p.push('مستبعد لأنه معيّن في خانة أخرى');p.push('الحالة: '+r.d.status);return p.join(' • ')}
function plan(entry,slotNo,driverId,proposal){requireRole('ADMIN','LEADER');if(mission(entry.mission_id).id==='forest')throw Error('الغابة لها مسار توزيع مستقل');const existing=state.assignments.filter(a=>a.schedule_entry_id===entry.id&&a.status!=='CANCELLED');if(existing.some(a=>a.slot_no===slotNo))throw Error('الخانة مخططة مسبقًا');const a={id:uid(),schedule_entry_id:entry.id,mission_id:entry.mission_id,slot_no:slotNo,planned_driver_id:driverId,actual_driver_id:null,due_driver_id:proposal?.dueRow?.d.id||null,status:'PLANNED',created_at:now(),decision_id:uid()};state.assignments.push(a);state.decisions.push({id:a.decision_id,ts:now(),assignment_id:a.id,mission_id:a.mission_id,recommended_driver_id:driverId,due_driver_id:a.due_driver_id,actual_driver_id:null,status:'PLANNED',override_reason:''});audit('assignments',a.id,'PLAN','',dname(driverId),'');persist('تم حفظ الخطة');return a}
function recordMissed(driverId,mid,slot,date,reason,replacementId){requireRole('ADMIN','LEADER');const key=state.missed.find(x=>!x.resolved&&x.driver_id===driverId&&x.mission_id===mid&&x.slot===slot);if(key)return key;const m={id:uid(),driver_id:driverId,mission_id:mid,slot:slot||null,date,reason,replacement_driver_id:replacementId||null,resolved:false,resolution_status:'OPEN',return_policy:state.settings.returnPolicy};state.missed.push(m);audit('missed_turns',m.id,'MISSED','OPEN','OPEN',reason);return m}
function confirmActual(aId,actualId,reason=''){requireRole('ADMIN','LEADER');const a=state.assignments.find(x=>x.id===aId);if(!a)throw Error('التوزيع غير موجود');if(a.status==='CANCELLED')throw Error('التوزيع ملغى');if(a.status==='CONFIRMED')throw Error('مؤكد مسبقًا');const entry=entries().find(e=>e.id===a.schedule_entry_id);const m=mission(a.mission_id);const planned=a.planned_driver_id;actualId=actualId||planned;const isRepl=planned!==actualId;if(isRepl&&!reason.trim())throw Error('تغيير المنفذ يتطلب سببًا');const others=state.assignments.filter(x=>x.schedule_entry_id===entry.id&&x.id!==a.id&&x.status!=='CANCELLED').map(x=>x.actual_driver_id||x.planned_driver_id).filter(Boolean);const p=propose(entry,a.slot_no,others,a.slot_no);const due=p.dueRow;a.due_driver_id=due?.d.id||a.due_driver_id||null;if(due&&due.d.id!==actualId){if(!due.eligible)recordMissed(due.d.id,m.id,null,entry.date,due.d.status==='عطلة'?'الدور فائت بسبب العطلة':'الدور له لكنه غير متاح',actualId);else audit('assignments',a.id,'OVERRIDE',due.d.id,actualId,reason)}a.actual_driver_id=actualId;a.is_replacement=isRepl;a.replacement_reason=reason.trim();a.status='CONFIRMED';a.confirmed_at=now();a.start_datetime=entry.instances[0].start.toISOString();a.end_datetime=entry.instances.at(-1).end.toISOString();state.assignments.push();if(a.decision_id){const d=state.decisions.find(x=>x.id===a.decision_id);if(d){d.actual_driver_id=actualId;d.status=isRepl?'OVERRIDDEN':'CONFIRMED';d.override_reason=reason.trim()}}const rb=restBefore(actualId,new Date(a.start_datetime));if(rb&&rb.hours<state.settings.minRest)a.rest_warning={hours:rb.hours,min:state.settings.minRest};audit('assignments',a.id,'CONFIRM','PLANNED','CONFIRMED',isRepl?reason:'');resolveReclaim(actualId,m.id);persist('تم تأكيد التنفيذ');return a}
function resolveReclaim(driverId,mid){const x=state.missed.find(m=>m.driver_id===driverId&&m.mission_id===mid&&!m.resolved&&m.return_policy==='RECLAIM');if(x){x.resolved=true;x.resolved_at=now();x.resolution_status='RESOLVED_BY_WORK';audit('missed_turns',x.id,'RESOLVED_BY_WORK','OPEN','RESOLVED','استرداد الدور عند العودة')}}
function cancelPlan(id){requireRole('ADMIN','LEADER');const a=state.assignments.find(x=>x.id===id);if(!a)throw Error('الخطة غير موجودة');if(a.status!=='PLANNED')throw Error('لا يمكن إلغاء توزيع غير مخطط');a.status='CANCELLED';a.cancelled_at=now();audit('assignments',id,'CANCEL_PLAN','PLANNED','CANCELLED','الصف محفوظ ولا يحذف');persist('أُلغيت الخطة وبقيت في السجل')}
function setStatus(id,status,reason=''){requireRole('ADMIN','LEADER');const d=driver(id);if(!d)throw Error('السائق غير موجود');const old=d.status;d.status=status;d.status_updated_at=now();audit('drivers',id,'STATUS',old,status,reason);persist('تم تحديث الحالة')}
function setMissedPolicy(id,policy){requireRole('ADMIN','LEADER');if(!['RECLAIM','NORMAL'].includes(policy))throw Error('سياسة غير صالحة');const x=state.missed.find(m=>m.id===id);if(!x)throw Error('الدور الفائت غير موجود');const old=x.return_policy;x.return_policy=policy;audit('missed_turns',id,'RETURN_POLICY',old,policy,policy==='RECLAIM'?'استرداد الدور عند العودة':'عودة طبيعية');persist('تم حفظ سياسة العودة')}
function resolveMissed(id){requireRole('ADMIN','LEADER');const x=state.missed.find(m=>m.id===id);if(!x)throw Error('الدور الفائت غير موجود');x.resolved=true;x.resolved_at=now();x.resolution_status='RESOLVED_MANUAL';audit('missed_turns',id,'RESOLVED_MANUAL','OPEN','RESOLVED','تسوية يدوية');persist('تمت التسوية')}
function addLoan(driverId,direction,reason){requireRole('ADMIN','LEADER');const x={id:uid(),driver_id:driverId,direction,date:now(),reason};state.loans.push(x);audit('loans',x.id,'LOAN', '',direction,reason);persist('تم تسجيل الاستلاف/التسليف')}
function assignForest(type,roleId,driverId,week,reason=''){requireRole('ADMIN','LEADER');if(!FOREST[type]?.some(x=>x.id===roleId))throw Error('دور غابة غير صالح');const ps=forestPeriods(week,type,roleId);if(ps.some(p=>overlaps(driverId,p.start,p.end).length))throw Error('السائق لديه تعارض زمني');ps.forEach((p,i)=>{const a={id:uid(),schedule_entry_id:week.id,mission_id:'forest',slot_no:null,forest_slot:roleId,forest_type:type,planned_driver_id:driverId,actual_driver_id:driverId,status:'CONFIRMED',created_at:now(),confirmed_at:now(),start_datetime:p.start.toISOString(),end_datetime:p.end.toISOString(),part:i+1,reason};state.assignments.push(a)});audit('forest',week.id,'FOREST_ASSIGN','',dname(driverId),reason);persist('تم اعتماد دور الغابة')}
function entries(){const w=getWeek();if(!w)return[];return MISSIONS.filter(m=>m.id!=='forest').map(m=>{const ps=periodsFor(m,w);return {id:w.id+'-'+m.id,week_id:w.id,date:dayDate(w.start,m.day),mission_id:m.id,instances:ps}})}
function forestAssignments(){return state.assignments.filter(a=>a.mission_id==='forest'&&a.status==='CONFIRMED')}
function createWeek(start){requireRole('ADMIN','LEADER');const s=sunday(start);if(state.weeks.some(w=>w.start===s))throw Error('الأسبوع موجود');state.weeks.unshift({id:uid(),start:s,createdAt:now()});audit('weeks',state.weeks[0].id,'CREATE','','',s);persist('تم إنشاء الأسبوع')}
function seedDemo(){requireRole('ADMIN');if(localStorage.getItem(KEY+'.demo'))throw Error('بيانات العرض موجودة مسبقًا');const w=getWeek()||(()=>{createWeek(iso(new Date()));return getWeek()})();const available=state.drivers.filter(eligible);for(const m of MISSIONS.filter(x=>x.id!=='forest')){const e={...entries().find(x=>x.mission_id===m.id),instances:periodsFor(m,w)};for(let s=1;s<=m.need;s++){const ex=state.assignments.filter(a=>a.schedule_entry_id===e.id&&a.status!=='CANCELLED').map(a=>a.planned_driver_id);const p=propose(e,s,ex);if(!p.recommended)break;const a=plan(e,s,p.recommended.d.id,p);confirmActual(a.id,a.planned_driver_id,'بيانات عرض')}}localStorage.setItem(KEY+'.demo','1');toast('تم إنشاء بيانات العرض مرة واحدة')}
function addUser(name,role){requireRole('ADMIN');if(!ROLES.includes(role))throw Error('دور غير صالح');const u={id:uid(),name,role};state.users.push(u);audit('users',u.id,'USER_ADD','','',name);persist('تمت إضافة المستخدم')}
function addTeam(name){requireRole('ADMIN','LEADER');const t={id:uid(),name};state.teams.push(t);audit('teams',t.id,'TEAM_ADD','','',name);persist('تمت إضافة الفرقة')}
function renderDashboard(){const w=getWeek();return `<h2>لوحة القيادة</h2><div class="grid"><div class="card"><small>الأسبوع الحالي</small><strong>${w?.start||'—'}</strong></div><div class="card"><small>السواق المتاحون</small><strong>${state.drivers.filter(eligible).length}</strong></div><div class="card"><small>التنفيذ المؤكد</small><strong>${state.assignments.filter(a=>a.status==='CONFIRMED').length}</strong></div><div class="card"><small>أدوار فائتة مفتوحة</small><strong>${state.missed.filter(x=>!x.resolved).length}</strong></div></div><h3>الحالة</h3><div class="driver-grid">${state.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><span class="pill">${esc(d.status)}</span><small>${history(d.id).length} فترات مؤكدة</small></div>`).join('')}</div>`}
function renderWeek(){const w=getWeek();if(!w)return '<div class="card">لا يوجد أسبوع. أنشئ الأسبوع الحالي.</div>';let h=`<h2>الأسبوع والمهام</h2><div class="card"><b>${w.start}</b> — الأحد إلى السبت</div>`;for(const e of entries()){const m=mission(e.mission_id);const as=state.assignments.filter(a=>a.schedule_entry_id===e.id&&a.status!=='CANCELLED');h+=`<div class="card"><h3>${esc(m.name)} <span class="chip mut">${m.need} سواق</span></h3><div class="mut">${e.instances.map(x=>x.start.toLocaleTimeString('ar-DZ',{hour:'2-digit',minute:'2-digit'})+'→'+x.end.toLocaleTimeString('ar-DZ',{hour:'2-digit',minute:'2-digit'})).join(' | ')}</div><div class="pill-row">${Array.from({length:m.need},(_,i)=>{const a=as.find(x=>x.slot_no===i+1);return a?`<span class="chip ${a.status==='CONFIRMED'?'ok':'info'}">${a.status==='CONFIRMED'?'فعلي':'خطة'} ${i+1}: ${esc(dname(a.actual_driver_id||a.planned_driver_id))}${a.due_driver_id&&a.due_driver_id!==(a.actual_driver_id||a.planned_driver_id)?' | الدور الأصلي: '+esc(dname(a.due_driver_id)):''}</span>`:`<span class="chip mut">خانة ${i+1}: شاغرة</span>`}).join('')}</div></div>`}return h}
function proposalHTML(e,slot){const ex=state.assignments.filter(a=>a.schedule_entry_id===e.id&&a.status!=='CANCELLED').map(a=>a.actual_driver_id||a.planned_driver_id);const p=propose(e,slot,ex);return `<div class="card"><h3>اقتراح: ${esc(p.mission.name)} — الخانة ${slot}</h3>${p.rows.map((r,i)=>`<div class="card"><b>${i+1}. ${esc(r.d.name)}</b> ${r.eligible?'':'<span class="chip err">غير مؤهل</span>'}${r.conf.length?'<span class="chip warn">تعارض</span>':''}<p class="mut">${esc(r.explain)}</p></div>`).join('')}<div class="card"><b>القرار الأصلي:</b> ${p.dueRow?esc(p.dueRow.f?.d?.name||p.dueRow.d.name):'—'}<br><b>الموصى به:</b> ${p.recommended?esc(p.recommended.d.name):'لا يوجد سائق مؤهل'}</div></div>`}
function renderAssign(){const w=getWeek();if(!w)return '<div class="card">أنشئ أسبوعًا أولًا.</div>';let h='<h2>التوزيع الفعلي</h2>';for(const e of entries()){const m=mission(e.mission_id),as=state.assignments.filter(a=>a.schedule_entry_id===e.id&&a.status!=='CANCELLED');h+=`<div class="card"><h3>${esc(m.name)}</h3>`;for(let s=1;s<=m.need;s++){const a=as.find(x=>x.slot_no===s);h+=`<div class="row"><span style="flex:1">الخانة ${s}: ${a?esc(dname(a.actual_driver_id||a.planned_driver_id)):'شاغرة'}</span>${!a?`<button class="btn sm" data-prop="${e.id}" data-slot="${s}">اقتراح</button>`:''}${a&&a.status==='PLANNED'?`<button class="btn sm" data-conf="${a.id}">تأكيد</button><button class="btn sm sec" data-change="${a.id}">تغيير المنفذ</button><button class="btn sm dng" data-cancel="${a.id}">إلغاء الخطة</button>`:''}</div>`}h+='</div>'}return h}
function renderDrivers(){return `<h2>السواق والاستثناءات</h2><div class="grid">${state.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><span class="pill">${esc(d.status)}</span><select data-status="${d.id}"><option>متاح</option><option>عطلة</option><option>عجز</option><option>مستعار</option><option>مسلف</option></select></div>`).join('')}</div><div class="card"><h3>الاستلاف والتسليف</h3><select id="loanDriver">${state.drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select><select id="loanDir"><option value="IN">استلاف لنا</option><option value="OUT">تسليف منا</option></select><input id="loanReason" placeholder="السبب"><button class="btn" id="loanAdd">حفظ</button></div>`}
function renderHistory(){const ev=state.events.slice().sort((a,b)=>b.ts.localeCompare(a.ts));return `<h2>السجل والمقارنة</h2><div class="card"><div class="tblwrap"><table><tr><th>الوقت</th><th>الكيان</th><th>الإجراء</th><th>من</th><th>إلى</th><th>السبب</th></tr>${ev.map(x=>`<tr><td>${fmt(x.ts)}</td><td>${esc(x.entity)}</td><td>${esc(x.action)}</td><td>${esc(x.from)}</td><td>${esc(x.to)}</td><td>${esc(x.reason)}</td></tr>`).join('')}</table></div></div>`}
function renderFairness(){const w=getWeek();if(!w)return '<div class="card">أنشئ أسبوعًا أولًا.</div>';const e=entries()[0];const p=e?propose(e,1):null;return `<h2>الدور القادم</h2><div class="card"><label>المهمة <select id="fairMission">${MISSIONS.filter(m=>m.id!=='forest').map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select></label><button class="btn" id="fairGo">تحليل الدور</button></div><div id="fairOut">${p?proposalHTML(e,1):''}</div><div class="card"><h3>الأدوار الفائتة</h3>${state.missed.filter(x=>!x.resolved).map(x=>`<div class="row"><span style="flex:1"><b>${esc(dname(x.driver_id))}</b> — ${esc(mission(x.mission_id)?.name||x.mission_id)} — ${fmt(x.date)} — ${esc(x.reason)}</span><span class="chip ${x.return_policy==='RECLAIM'?'ok':'info'}">${x.return_policy==='RECLAIM'?'استرداد':'عودة طبيعية'}</span><button class="btn sm sec" data-policy="${x.id}">تغيير</button><button class="btn sm" data-resolve="${x.id}">تسوية</button></div>`).join('')||'<div class="mut">لا يوجد.</div>'}</div>`}
function render(){const active=document.querySelector('.tabs .active')?.dataset.tab||'dashboard';const map={dashboard:renderDashboard,week:renderWeek,assign:renderAssign,drivers:renderDrivers,history:renderHistory,fairness:renderFairness};for(const k of Object.keys(map)){const e=document.getElementById(k);if(e)e.innerHTML=k===active?map[k]():''}bind()}
function bind(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});document.querySelectorAll('[data-prop]').forEach(b=>b.onclick=()=>{try{const e=entries().find(x=>x.id===b.dataset.prop);openModal(proposalHTML(e,+b.dataset.slot),()=>{const p=propose(e,+b.dataset.slot,state.assignments.filter(a=>a.schedule_entry_id===e.id&&a.status!=='CANCELLED').map(a=>a.actual_driver_id||a.planned_driver_id));if(!p.recommended)throw Error('لا يوجد مؤهل');plan(e,+b.dataset.slot,p.recommended.d.id,p)})}catch(e){toast(e.message)}});document.querySelectorAll('[data-conf]').forEach(b=>b.onclick=()=>{try{confirmActual(b.dataset.conf); }catch(e){toast(e.message)}});document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const ids=state.drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');openModal('<h3>تغيير المنفذ</h3><select id="actualSel">'+ids+'</select><input id="actualReason" placeholder="سبب التغيير"><button class="btn" id="actualSave">تأكيد</button>',()=>{document.getElementById('actualSave').onclick=()=>{try{confirmActual(b.dataset.change,document.getElementById('actualSel').value,document.getElementById('actualReason').value);closeModal()}catch(e){toast(e.message)}}})});document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>{try{cancelPlan(b.dataset.cancel)}catch(e){toast(e.message)}});document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{try{setStatus(s.dataset.status,s.value,'تغيير من شاشة السواق')}catch(e){toast(e.message);render()}});document.getElementById('loanAdd')?.addEventListener('click',()=>{try{addLoan(loanDriver.value,loanDir.value,loanReason.value)}catch(e){toast(e.message)}});document.querySelectorAll('[data-resolve]').forEach(b=>b.onclick=()=>{try{resolveMissed(b.dataset.resolve)}catch(e){toast(e.message)}});document.querySelectorAll('[data-policy]').forEach(b=>b.onclick=()=>{const x=state.missed.find(m=>m.id===b.dataset.policy);const p=x.return_policy==='RECLAIM'?'NORMAL':'RECLAIM';try{setMissedPolicy(x.id,p)}catch(e){toast(e.message)}});document.getElementById('fairGo')?.addEventListener('click',()=>{const mid=fairMission.value,e=entries().find(x=>x.mission_id===mid);if(e)document.getElementById('fairOut').innerHTML=proposalHTML(e,1)});document.getElementById('exportBtn')?.addEventListener('click',exportDB);document.getElementById('importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click());document.getElementById('importFile')?.addEventListener('change',e=>importDB(e.target.files[0]))}
function openModal(html,after){let m=document.getElementById('modal');if(!m){m=document.createElement('div');m.id='modal';m.className='modal';document.body.appendChild(m)}m.innerHTML='<div class="modal-box">'+html+'<button class="btn sec" id="modalClose">إغلاق</button></div>';m.hidden=false;document.getElementById('modalClose').onclick=closeModal;after?.()}
function closeModal(){const m=document.getElementById('modal');if(m)m.hidden=true}
function exportDB(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='sowa9-v6-backup.json';a.click()}
function importDB(file){if(!file)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x.version!==6||!x.drivers||!x.assignments||!x.missed)throw Error('نسخة بيانات غير مدعومة');requireRole('ADMIN');state=x;localStorage.setItem(KEY,JSON.stringify(state));render();toast('تم الاستيراد')}catch(e){toast(e.message)}};r.readAsText(file)}
function runTests(){const out=[];const t=(n,fn)=>{try{fn();out.push(['PASS',n])}catch(e){out.push(['FAIL',n,e.message])}};t('01 schema',()=>{if(state.version!==6)throw Error('version')});t('02 drivers',()=>{if(state.drivers.length<1)throw Error('drivers')});t('03 statuses',()=>{if(state.drivers.some(d=>!STATUSES.includes(d.status)))throw Error('status')});t('04 missions',()=>{if(MISSIONS.length!==10)throw Error('missions')});t('05 Sunday',()=>{if(sunday('2026-08-30')!=='2026-08-30')throw Error('sunday')});t('06 periods',()=>{const w=getWeek()||{start:sunday(iso(new Date()))};if(periodsFor(MISSIONS[0],w).length!==1)throw Error('period')});t('07 overnight',()=>{const w=getWeek()||{start:sunday(iso(new Date()))};if(hours(...Object.values(periodsFor(MISSIONS[1],w)[0]).map(x=>x.toISOString()))!==7)throw Error('overnight')});t('08 history',()=>{history(state.drivers[0].id)});t('09 no cancelled in active',()=>{const a=state.assignments.filter(x=>x.status==='CANCELLED');if(a.some(x=>x.status!=='CANCELLED'))throw Error('cancel')});t('10 deterministic proposal',()=>{const w=getWeek()||{start:sunday(iso(new Date()))},e={id:'t',mission_id:'bahja',instances:periodsFor(mission('bahja'),w)};const a=propose(e,1,[]),b=propose(e,1,[]);if(a.dueRow?.d.id!==b.dueRow?.d.id)throw Error('nondeterministic')});t('11 missed policy',()=>{if(!['RECLAIM','NORMAL'].includes(state.settings.returnPolicy))throw Error('policy')});t('12 roles',()=>{if(state.users.some(u=>!ROLES.includes(u.role)))throw Error('role')});t('13 audit',()=>{if(!Array.isArray(state.events))throw Error('events')});t('14 decisions',()=>{if(!Array.isArray(state.decisions))throw Error('decisions')});t('15 assignments',()=>{if(!Array.isArray(state.assignments))throw Error('assignments')});t('16 loans',()=>{if(!Array.isArray(state.loans))throw Error('loans')});t('17 missed',()=>{if(!Array.isArray(state.missed))throw Error('missed')});t('18 forest',()=>{if(FOREST.Alpha.length!==2||FOREST.MO.length!==2)throw Error('forest')});t('19 forest gap',()=>{const w=getWeek()||{start:sunday(iso(new Date()))};const p=forestPeriods(w,'Alpha','alpha_middle');if(p.length!==1)throw Error('forest')});t('20 min rest',()=>{if(state.settings.minRest<=0)throw Error('rest')});t('21 immutable cancel',()=>{if(state.assignments.some(a=>a.status==='CANCELLED'&&!a.cancelled_at))throw Error('cancel marker')});t('22 import/export shape',()=>{JSON.stringify(state)});t('23 replacement field',()=>{state.assignments.forEach(a=>{if(a.is_replacement&&!a.replacement_reason)throw Error('reason')})});t('24 due field',()=>{state.assignments.forEach(a=>{if(a.status==='CONFIRMED'&&a.due_driver_id===undefined)throw Error('due')})});t('25 no fake forest normal',()=>{state.assignments.filter(a=>a.mission_id==='forest').forEach(a=>{if(a.slot_no!==null)throw Error('forest slot')})});t('26 one-device local',()=>{if(!('localStorage' in window))throw Error('storage')});return out}
function showTests(){const r=runTests();openModal('<h3>الاختبارات 26</h3><pre>'+r.map(x=>x[0]==='PASS'?'✓ '+x[1]:'✗ '+x[1]+' — '+x[2]).join('\n')+'</pre>',null)}
window.Sowa9={state,propose,runTests,showTests,createWeek,seedDemo};
ensureCurrentWeek();
document.addEventListener('DOMContentLoaded',()=>{render();document.getElementById('exportBtn')?.addEventListener('click',exportDB);document.getElementById('importBtn')?.addEventListener('click',()=>document.getElementById('importFile').click())});
