const KEY='sowa9.v2';
const DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const DRIVERS=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const BASE_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز طبي',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',name:'دنيا برك',seq:1,day:'الأحد',periods:[['12:00','22:00']],need:2,night:false,note:''},
{id:'garden',name:'غاردن سيتي',seq:2,day:'الأحد',periods:[['17:00','00:00']],need:2,night:true,note:''},
{id:'bahja',name:'البحر — بهجة',seq:3,day:'الثلاثاء',periods:[['09:00','22:00']],need:1,night:false,note:'خارجي ومتعب بسبب الحرارة؛ بهجة أصعب.'},
{id:'club',name:'البحر — كلوب',seq:4,day:'الثلاثاء',periods:[['12:00','22:00']],need:3,night:false,note:'خارجي ومتعب بسبب الحرارة.'},
{id:'bondage',name:'بونداج زرالدة',seq:5,day:'الأربعاء',periods:[['04:30','10:00']],need:2,night:false,note:''},
{id:'guard',name:'حراسة',seq:6,day:'الأربعاء',periods:[['17:00','00:00']],need:1,night:true,note:'داخلي ومريح، لكنه يُحسب عملًا ليليًا.'},
{id:'raids',name:'مداهمات',seq:7,day:'الخميس',periods:[['19:30','05:00']],need:2,night:true,note:'عمل خارجي ليلي.'},
{id:'delivery',name:'توصيل',seq:8,day:'الخميس',periods:[['20:00','21:30'],['06:30','08:00']],need:1,night:false,note:'فترتان منفصلتان.'},
{id:'barajat',name:'براجات',seq:9,day:'الجمعة',periods:[['06:00','12:00']],need:1,night:false,note:'داخلي ومريح.'},
{id:'forest',name:'الغابة',seq:10,day:'الجمعة',periods:[],need:4,night:false,note:'24 ساعة. أربعة سائقين: Alpha أو MO.'}
];
const FOREST={
 Alpha:[['بداية','17:00','23:00'],['وسط','05:00','11:00'],['نهاية','11:00','17:00']],
 MO:[['بداية','17:00','22:00'],['وسط','07:00','12:00'],['نهاية','12:00','17:00']]
};
function fresh(){return {drivers:DRIVERS.map((name,i)=>({id:i+1,name,status:BASE_STATUS[name]})),weeks:[],assignments:[],loans:[],missed:[],events:[]}}
let db=JSON.parse(localStorage.getItem(KEY)||'null');
if(!db){db=fresh()}else{db=Object.assign(fresh(),db);db.drivers=db.drivers?.length?db.drivers:fresh().drivers}
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function iso(d){return d.toISOString().slice(0,10)}
function sundayOf(s){const x=new Date(s+'T12:00');x.setDate(x.getDate()-x.getDay());return iso(x)}
function dateForDay(start,day){const x=new Date(start+'T12:00');x.setDate(x.getDate()+DAYS.indexOf(day));return iso(x)}
function dt(start,day,time,overnight=false){const x=new Date(`${dateForDay(start,day)}T${time}:00`);if(overnight)x.setDate(x.getDate()+1);return x}
function fmt(v){return new Date(v).toLocaleString('ar-DZ',{dateStyle:'short',timeStyle:'short'})}
function hours(a,b){return (new Date(b)-new Date(a))/3600000}
function mission(id){return MISSIONS.find(m=>m.id===id)}
function week(){return db.weeks[0]}
function active(){return db.drivers.filter(d=>['متاح','مستعار'].includes(d.status))}
function allHistory(id){return db.assignments.filter(a=>a.driverId===id).sort((a,b)=>new Date(a.start)-new Date(b.start))}
function lastFor(id,missionId,role=null,forestType=null){return db.assignments.filter(a=>a.driverId===id&&a.missionId===missionId&&(!role||a.role===role)&&(!forestType||a.forestType===forestType)).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]||null}
function lastOverall(id){return allHistory(id).at(-1)||null}
function restBefore(id,start){const h=allHistory(id).filter(a=>new Date(a.end)<=new Date(start));if(!h.length)return null;const p=h.at(-1);return {previous:p,from:p.end,to:start,hours:hours(p.end,start)} }
function currentWeekAssignments(){const w=week();return w?db.assignments.filter(a=>a.weekId===w.id):[]}
function createWeek(start){start=sundayOf(start);if(db.weeks.some(w=>w.start===start)){toast('الأسبوع موجود');return}db.weeks.unshift({id:crypto.randomUUID(),start,createdAt:new Date().toISOString()});save();toast('تم إنشاء الأسبوع')}
function markMissed(missionId,driverId,weekId,reason){if(!db.missed.some(x=>x.weekId===weekId&&x.missionId===missionId&&x.driverId===driverId&&!x.resolved)){db.missed.push({id:crypto.randomUUID(),weekId,missionId,driverId,reason,date:new Date().toISOString(),resolved:false})}}
function recordAssignment({weekId,missionId,driverId,start,end,role='',forestType='',replacement=false,reason=''}){db.assignments.push({id:crypto.randomUUID(),weekId,missionId,driverId,start,end,role,forestType,replacement,reason,createdAt:new Date().toISOString()})}
function candidates(missionId,role='',forestType=''){
 const ms=active();
 return ms.map(d=>{const exact=lastFor(d.id,missionId,role||null,forestType||null);const same=lastFor(d.id,missionId);const overall=lastOverall(d.id);const missed=db.missed.filter(x=>x.driverId===d.id&&x.missionId===missionId&&!x.resolved).length;const rest=overall?hours(overall.end,new Date()):Infinity;return {d,exact,same,overall,missed,rest,count:db.assignments.filter(a=>a.driverId===d.id&&a.missionId===missionId).length}}).sort((a,b)=>{
   if(a.missed!==b.missed)return b.missed-a.missed;
   if(!a.exact&&!b.exact){if(!a.same&&!b.same)return a.d.id-b.d.id;if(!a.same)return -1;if(!b.same)return 1}
   if(!a.exact)return -1;if(!b.exact)return 1;
   const t=new Date(a.exact.start)-new Date(b.exact.start);if(t)return t;
   if(a.count!==b.count)return a.count-b.count;
   const ao=a.overall?new Date(a.overall.start).getTime():-Infinity,bo=b.overall?new Date(b.overall.start).getTime():-Infinity;return ao-bo;
 });
}
function suggestion(missionId,role='',forestType=''){const c=candidates(missionId,role,forestType);return c[0]||null}
function forestPeriods(type){return FOREST[type]||[]}
function forestDatePeriods(w,type){const base=dateForDay(w.start,'الجمعة');return forestPeriods(type).map((p,i)=>{let dayOffset=i===0?0:1;const s=new Date(`${base}T${p[1]}:00`);s.setDate(s.getDate()+dayOffset);const e=new Date(`${base}T${p[2]}:00`);e.setDate(e.getDate()+dayOffset);return {role:p[0],start:s,end:e}})}
function renderDashboard(){const w=week();const ca=active().length;document.getElementById('dashboard').innerHTML=`<h2>لوحة القيادة</h2><div class="grid"><div class="card"><h3>الأسبوع الحالي</h3><div class="metric">${w?esc(w.start):'—'}</div><p class="muted">إعادة الحساب أسبوعية، والسجل التاريخي لا يُحذف.</p></div><div class="card"><h3>السواق المتاحون</h3><div class="metric">${ca}</div></div><div class="card"><h3>التوزيعات المسجلة</h3><div class="metric">${db.assignments.length}</div></div><div class="card"><h3>الاستلاف/التسليف</h3><div class="metric">${db.loans.length}</div></div></div><h3>الحالة الحالية</h3><div class="grid">${db.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><p>${esc(d.status)}</p><span class="pill">${allHistory(d.id).length} توزيع تاريخي</span></div>`).join('')}</div>`}
function renderWeek(){const el=document.getElementById('week');const w=week();el.innerHTML=`<h2>الأسبوع</h2><div class="toolbar"><div class="field"><label>بداية الأسبوع (الأحد)</label><input type="date" id="newWeek" value="${w?.start||sundayOf(iso(new Date()))}"></div><button id="makeWeek">إنشاء أسبوع</button></div>${w?`<div class="table-wrap"><table><thead><tr><th>#</th><th>اليوم</th><th>المهمة</th><th>الفترات</th><th>المطلوب</th><th>ليل؟</th><th>ملاحظة</th></tr></thead><tbody>${MISSIONS.map(m=>`<tr><td>${m.seq}</td><td>${m.day}</td><td><b>${m.name}</b></td><td>${m.id==='forest'?'Alpha / MO':m.periods.map(p=>p.join('→')).join(' + ')}</td><td>${m.need}</td><td>${m.night?'نعم':'لا'}</td><td>${esc(m.note)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">أنشئ أول أسبوع.</div>'}`;document.getElementById('makeWeek').onclick=()=>createWeek(document.getElementById('newWeek').value)}
function renderAssign(){const el=document.getElementById('assign');const w=week();if(!w){el.innerHTML='<div class="empty">أنشئ أسبوعًا أولًا.</div>';return}const ds=active();el.innerHTML=`<h2>التوزيع الفعلي</h2><div class="card"><div class="toolbar"><div class="field"><label>المهمة</label><select id="amission">${MISSIONS.map(m=>`<option value="${m.id}">${m.seq}. ${m.name}</option>`).join('')}</select></div><div class="field" id="forestWrap" style="display:none"><label>الغابة</label><select id="forestType"><option>Alpha</option><option>MO</option></select></div><div class="field" id="roleWrap" style="display:none"><label>الدور</label><select id="role"><option>بداية</option><option>وسط</option><option>نهاية</option></select></div><div class="field"><label>السائق</label><select id="adriver">${ds.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>البداية</label><input type="datetime-local" id="astart"></div><div class="field"><label>النهاية</label><input type="datetime-local" id="aend"></div><div class="field"><label>استثناء/سبب</label><input id="reason" placeholder="اختياري"></div><button id="suggest">اقتراح حسب السجل</button><button id="addA">تسجيل التوزيع</button></div><div id="suggestion"></div></div><h3>توزيعات الأسبوع</h3>${weekTable(w.id)}`;
 const refresh=()=>{const m=mission(document.getElementById('amission').value);const f=m.id==='forest';document.getElementById('forestWrap').style.display=f?'flex':'none';document.getElementById('roleWrap').style.display=f?'flex':'none';if(!f){const p=m.periods[0];const s=dt(w.start,m.day,p[0]);const e=dt(w.start,m.day,p[1],p[1]<=p[0]);document.getElementById('astart').value=s.toISOString().slice(0,16);document.getElementById('aend').value=e.toISOString().slice(0,16)}else{const fp=forestDatePeriods(w,document.getElementById('forestType').value);const r=document.getElementById('role').value;const p=fp.find(x=>x.role===r)||fp[0];document.getElementById('astart').value=p.start.toISOString().slice(0,16);document.getElementById('aend').value=p.end.toISOString().slice(0,16)}};
 document.getElementById('amission').onchange=refresh;document.getElementById('forestType').onchange=refresh;document.getElementById('role').onchange=refresh;refresh();
 document.getElementById('suggest').onclick=()=>{const m=mission(document.getElementById('amission').value);const r=m.id==='forest'?document.getElementById('role').value:'';const f=m.id==='forest'?document.getElementById('forestType').value:'';const cs=candidates(m.id,r,f);if(!cs.length)return;document.getElementById('adriver').value=cs[0].d.id;document.getElementById('suggestion').innerHTML=`<div class="reason"><b>المقترح: ${esc(cs[0].d.name)}</b><br>${cs[0].exact?`آخر نفس الدور: ${fmt(cs[0].exact.start)}`:'لم يعمل هذا الدور في السجل.'}<br>${cs[0].same?`آخر نفس المهمة: ${fmt(cs[0].same.start)}`:'لم يعمل هذه المهمة في السجل.'}<br><br>${cs.map((c,i)=>`${i+1}. ${esc(c.d.name)} — ${c.exact?'آخر الدور '+fmt(c.exact.start):'لا سجل لهذا الدور'} — ${c.same?'آخر المهمة '+fmt(c.same.start):'لا سجل للمهمة'} — ${c.missed?'دور فائت: '+c.missed:'لا دور فائت'}`).join('<br>')}</div>`};
 document.getElementById('addA').onclick=()=>{const m=mission(document.getElementById('amission').value),driverId=+document.getElementById('adriver').value,reason=document.getElementById('reason').value.trim();if(m.id==='forest'){const type=document.getElementById('forestType').value,r=document.getElementById('role').value,p=forestDatePeriods(w,type).find(x=>x.role===r);recordAssignment({weekId:w.id,missionId:m.id,driverId,start:p.start.toISOString(),end:p.end.toISOString(),role:r,forestType:type,replacement:!!reason,reason});}else{recordAssignment({weekId:w.id,missionId:m.id,driverId,start:new Date(document.getElementById('astart').value).toISOString(),end:new Date(document.getElementById('aend').value).toISOString(),replacement:!!reason,reason})}save();toast('تم تسجيل التوزيع')}}
function weekTable(id){const xs=db.assignments.filter(a=>a.weekId===id).sort((a,b)=>new Date(a.start)-new Date(b.start));if(!xs.length)return '<div class="empty">لا توجد توزيعات فعلية.</div>';return `<div class="table-wrap"><table><thead><tr><th>السائق</th><th>اليوم/المهمة</th><th>الدور</th><th>الفترة</th><th>الراحة قبلها</th><th>الاستثناء</th></tr></thead><tbody>${xs.map(a=>{const d=db.drivers.find(x=>x.id===a.driverId),m=mission(a.missionId),r=restBefore(a.driverId,a.start);return `<tr><td><b>${esc(d?.name)}</b></td><td>${m?.day}<br>${m?.name}</td><td>${a.forestType?`${a.forestType} — ${a.role}`:'—'}</td><td>${fmt(a.start)}<br>→ ${fmt(a.end)}<br><b>${hours(a.start,a.end).toFixed(1)} ساعة</b></td><td>${r?`${fmt(r.from)}<br>→ ${fmt(r.to)}<br><b>${r.hours.toFixed(1)} ساعة متصلة</b>`:'لا عمل سابق'}</td><td>${a.replacement?esc(a.reason):'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function renderDrivers(){document.getElementById('drivers').innerHTML=`<h2>السواق والحالات</h2><div class="grid">${db.drivers.map(d=>`<div class="card"><h3>${esc(d.name)}</h3><select data-status="${d.id}"><option ${d.status==='متاح'?'selected':''}>متاح</option><option ${d.status==='عطلة'?'selected':''}>عطلة</option><option ${d.status==='عجز طبي'?'selected':''}>عجز طبي</option><option ${d.status==='مستعار'?'selected':''}>مستعار</option><option ${d.status==='مسلف'?'selected':''}>مسلف</option></select><p class="small">آخر مهمة: ${lastOverall(d.id)?mission(lastOverall(d.id).missionId)?.name:'لا يوجد'}</p></div>`).join('')}</div>`;document.querySelectorAll('[data-status]').forEach(x=>x.onchange=()=>{const d=db.drivers.find(d=>d.id==x.dataset.status);d.status=x.value;db.events.push({type:'status',driverId:d.id,status:d.status,at:new Date().toISOString()});save()})}
function renderHistory(){const el=document.getElementById('history');const rows=db.drivers.map(d=>{const hs=allHistory(d.id);return `<div class="card"><h3>${esc(d.name)}</h3>${hs.length?hs.slice().reverse().slice(0,30).map(a=>{const m=mission(a.missionId),r=restBefore(d.id,a.start);return `<div class="mission"><strong>${m?.name}${a.forestType?' — '+a.forestType+' / '+a.role:''}</strong><span>${fmt(a.start)} → ${fmt(a.end)} (${hours(a.start,a.end).toFixed(1)} ساعة)</span>${r?`<div class="rest">راحة قبلها: من ${fmt(r.from)} إلى ${fmt(r.to)} = ${r.hours.toFixed(1)} ساعة متصلة</div>`:''}</div>`}).join(''):'<p class="muted">لا يوجد سجل.</p>'}</div>`}).join('');el.innerHTML=`<h2>السجل والمقارنة</h2><p class="muted">يعرض آخر الأعمال، الأوقات، أدوار الغابة، وفترة الراحة المتصلة قبل كل مهمة. لا يتم حذف السجل عند إعادة الحساب الأسبوعي.</p><div class="grid">${rows}</div>`}
function renderFairness(){const el=document.getElementById('fairness');if(!week()){el.innerHTML='<div class="empty">أنشئ أسبوعًا أولًا.</div>';return}el.innerHTML=`<h2>الدور القادم</h2><p class="muted">الأولوية تُستخرج من التاريخ الحقيقي: آخر نفس الدور، آخر نفس المهمة، الأدوار الفائتة، ثم ترتيب السجل. لا توجد نقاط مصطنعة.</p><div class="grid">${MISSIONS.map(m=>{const r=m.id==='forest'?'بداية':'';const f=m.id==='forest'?'Alpha':'';const s=suggestion(m.id,r,f);return `<div class="card"><h3>${m.seq}. ${m.name}</h3><p>المقترح: <b>${s?esc(s.d.name):'لا يوجد متاح'}</b></p>${s?`<p class="small">${s.exact?'آخر الدور: '+fmt(s.exact.start):'لم يعمل الدور من قبل'}<br>${s.same?'آخر المهمة: '+fmt(s.same.start):'لم يعمل المهمة من قبل'}<br>آخر عمل إجمالًا: ${s.overall?fmt(s.overall.start):'لا يوجد'}</p>`:''}</div>`}).join('')}</div>`}
function renderAll(){renderDashboard();renderWeek();renderAssign();renderDrivers();renderHistory();renderFairness()}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sowa9-backup.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();
document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();toast('تم الاستيراد')}catch{toast('ملف غير صالح')}};r.readAsText(f)};
renderAll();