const KEY='sowa9.v1';
const DRIVERS=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const BASE_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز طبي',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',name:'دنيا برك',seq:1,day:'الأحد',start:'12:00',end:'22:00',need:2,night:false,note:''},
{id:'garden',name:'غاردن سيتي',seq:2,day:'الأحد',start:'17:00',end:'00:00',need:2,night:true,note:''},
{id:'bahja',name:'البحر — بهجة',seq:3,day:'الثلاثاء',start:'09:00',end:'22:00',need:1,night:false,note:'خارجي ومتعب بسبب الحرارة؛ بهجة أصعب.'},
{id:'club',name:'البحر — كلوب',seq:4,day:'الثلاثاء',start:'12:00',end:'22:00',need:3,night:false,note:'خارجي ومتعب بسبب الحرارة.'},
{id:'bondage',name:'بونداج زرالدة',seq:5,day:'الأربعاء',start:'04:30',end:'10:00',need:2,night:false,note:''},
{id:'guard',name:'حراسة',seq:6,day:'الأربعاء',start:'17:00',end:'00:00',need:1,night:true,note:'داخلي ومريح، لكنه يُحسب عملًا ليليًا.'},
{id:'raids',name:'مداهمات',seq:7,day:'الخميس',start:'19:30',end:'05:00',need:2,night:true,note:'عمل خارجي ليلي.'},
{id:'delivery',name:'توصيل',seq:8,day:'الخميس',start:'20:00',end:'21:30 + 06:30→08:00',need:1,night:false,note:'فترتان منفصلتان.'},
{id:'barajat',name:'براجات',seq:9,day:'الجمعة',start:'06:00',end:'12:00',need:1,night:false,note:'داخلي ومريح.'},
{id:'forest',name:'الغابة',seq:10,day:'الجمعة',start:'17:00',end:'17:00+1',need:3,night:false,note:'24 ساعة؛ Alpha أو MO.'}
];
const FOREST={Alpha:[['بداية','17:00','23:00'],['وسط','05:00','11:00'],['نهاية','11:00','17:00']],MO:[['بداية','17:00','22:00'],['وسط','07:00','12:00'],['نهاية','12:00','17:00']]};
function fresh(){return {drivers:DRIVERS.map((name,i)=>({id:i+1,name,status:BASE_STATUS[name]})),weeks:[],assignments:[],loans:[],missed:[]}}
let db=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function iso(d){return d.toISOString().slice(0,10)}
function mondayOf(d){const x=new Date(d+'T12:00');const n=x.getDay();const delta=n===0?-6:1-n;x.setDate(x.getDate()+delta);return iso(x)}
function dateForDay(weekStart,day){const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];const idx=days.indexOf(day);const m=new Date(weekStart+'T12:00');const monday=m.getDay()===0?-6:1-m.getDay();m.setDate(m.getDate()+monday+(idx===0?6:idx-1));return iso(m)}
function dt(weekStart,day,time,add=0){let d=new Date(`${dateForDay(weekStart,day)}T${time}:00`);d.setDate(d.getDate()+add);return d}
function dur(a,b){return (b-a)/36e5}
function week(){return db.weeks.find(w=>w.id===document.getElementById('weekSelect')?.value)||db.weeks[0]}
function currentWeek(){return db.weeks[0]}
function createWeek(start){start=mondayOf(start);if(db.weeks.some(w=>w.start===start)){toast('الأسبوع موجود');return}db.weeks.unshift({id:crypto.randomUUID(),start,createdAt:new Date().toISOString()});save();toast('تم إنشاء الأسبوع')}
function activeDriverIds(){return db.drivers.filter(d=>d.status==='متاح'||d.status==='مستعار').map(d=>d.id)}
function lastAssignment(driverId, missionId, role=null){const xs=db.assignments.filter(a=>a.driverId===driverId && a.missionId===missionId && (!role||a.role===role)).sort((a,b)=>new Date(b.start)-new Date(a.start));return xs[0]||null}
function history(driverId){return db.assignments.filter(a=>a.driverId===driverId).sort((a,b)=>new Date(a.start)-new Date(b.start))}
function restBefore(driverId,start){const h=history(driverId).filter(a=>new Date(a.end)<=new Date(start));if(!h.length)return null;const p=h[h.length-1];return {from:p.end,to:start,hours:dur(new Date(p.end),new Date(start)),previous:p}}
function candidate(missionId,role=null){const arr=db.drivers.filter(d=>d.status==='متاح'||d.status==='مستعار');const all=arr.map(d=>{const last=lastAssignment(d.id,missionId,role);const allLast=history(d.id).at(-1);return {d,last,allLast,count:db.assignments.filter(a=>a.driverId===d.id&&a.missionId===missionId).length,rest:allLast?dur(new Date(allLast.end),new Date()):Infinity}});all.sort((a,b)=>{if(!a.last&&!b.last)return a.d.id-b.d.id;if(!a.last)return -1;if(!b.last)return 1;const t=new Date(a.last.start)-new Date(b.last.start);if(t)return t;return a.count-b.count});return all}
function recordAssignment(weekId,missionId,driverId,start,end,role='',forestType='',replacement=false,reason=''){db.assignments.push({id:crypto.randomUUID(),weekId,missionId,driverId,start,end,role,forestType,replacement,reason,createdAt:new Date().toISOString()})}
function missionById(id){return MISSIONS.find(m=>m.id===id)}
function renderDashboard(){const el=document.getElementById('dashboard');const w=currentWeek();const counts=db.drivers.map(d=>({d,n:db.assignments.filter(a=>a.driverId===d.id).length}));el.innerHTML=`<h2>لوحة القيادة</h2><div class="grid"><div class="card"><h3>الأسبوع الحالي</h3><div class="metric">${w?esc(w.start):'—'}</div><p class="muted">الحساب الأسبوعي يعاد، والسجل لا يحذف.</p></div><div class="card"><h3>السائقون المتاحون</h3><div class="metric">${activeDriverIds().length}</div></div><div class="card"><h3>التوزيعات المسجلة</h3><div class="metric">${db.assignments.length}</div></div><div class="card"><h3>الاستلاف/التسليف</h3><div class="metric">${db.loans.length}</div></div></div><h3>الحالة الحالية</h3><div class="grid">${db.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><p>${esc(d.status)}</p><span class="pill">${db.assignments.filter(a=>a.driverId===d.id).length} توزيع تاريخي</span></div>`).join('')}</div>`}
function weekOptions(){return db.weeks.map(w=>`<option value="${w.id}">${w.start}</option>`).join('')}
function renderWeek(){const el=document.getElementById('week');const w=currentWeek();el.innerHTML=`<h2>الأسبوع</h2><div class="toolbar"><div class="field"><label>بداية الأسبوع</label><input type="date" id="newWeek" value="${w?.start||mondayOf(iso(new Date()))}"></div><button id="makeWeek">إنشاء أسبوع</button></div>${db.weeks.length?`<div class="table-wrap"><table><thead><tr><th>الترتيب</th><th>اليوم</th><th>المهمة</th><th>الوقت</th><th>المطلوب</th><th>تصنيف الوقت</th></tr></thead><tbody>${MISSIONS.map(m=>`<tr><td>${m.seq}</td><td>${m.day}</td><td><b>${m.name}</b><div class="small muted">${esc(m.note)}</div></td><td>${m.start}→${m.end}</td><td>${m.need}</td><td>${m.night?'ليلي':'غير ليلي'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">أنشئ أول أسبوع.</div>'}`;document.getElementById('makeWeek').onclick=()=>createWeek(document.getElementById('newWeek').value)}
function renderAssign(){const el=document.getElementById('assign');const w=currentWeek();if(!w){el.innerHTML='<div class="empty">أنشئ أسبوعًا أولًا.</div>';return}const active=db.drivers.filter(d=>d.status==='متاح'||d.status==='مستعار');el.innerHTML=`<h2>التوزيع الفعلي</h2><div class="card"><div class="toolbar"><div class="field"><label>المهمة</label><select id="amission">${MISSIONS.map(m=>`<option value="${m.id}">${m.seq}. ${m.name}</option>`).join('')}</select></div><div class="field"><label>نوع الغابة</label><select id="forestType"><option value="">—</option><option>Alpha</option><option>MO</option></select></div><div class="field"><label>الدور</label><select id="role"><option value="">عادي</option><option>بداية</option><option>وسط</option><option>نهاية</option></select></div><div class="field"><label>السائق</label><select id="adriver">${active.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>البداية</label><input type="datetime-local" id="astart"></div><div class="field"><label>النهاية</label><input type="datetime-local" id="aend"></div><button id="addA">تسجيل التوزيع</button><button id="suggest">اقتراح حسب السجل</button></div><p class="small muted">التسجيل هنا فعلي؛ الاستثناءات يمكن توثيق سببها في السجل.</p><div id="suggestion"></div></div><h3>توزيعات الأسبوع</h3>${weekTable(w.id)}`;document.getElementById('amission').onchange=()=>setDefaultTimes(w);setDefaultTimes(w);document.getElementById('suggest').onclick=()=>showSuggestion();document.getElementById('addA').onclick=addAssignment}
function setDefaultTimes(w){const m=missionById(document.getElementById('amission').value);const d=dateForDay(w.start,m.day);let endDay=d;if(m.end.startsWith('00')||m.end.startsWith('05')){let x=new Date(d+'T'+m.end.split(' ')[0]+':00');if(m.end==='00:00'||m.end==='05:00')x.setDate(x.getDate()+1);endDay=iso(x)}document.getElementById('astart').value=`${d}T${m.start}`;document.getElementById('aend').value=`${endDay}T${m.end.includes(' ')||m.end.includes('→')?m.start:m.end}`}
function showSuggestion(){const m=missionById(document.getElementById('amission').value);const role=document.getElementById('role').value||null;const cs=candidate(m.id,role);document.getElementById('suggestion').innerHTML=cs.length?`<div class="reason"><b>الأولوية المقترحة: ${esc(cs[0].d.name)}</b><br>السبب: ${cs[0].last?'آخر عمل مسجل لهذه المهمة أقدم من بقية المرشحين.':'لم يعمل هذه المهمة سابقًا في السجل.'}<br><br>${cs.map((c,i)=>`${i+1}. ${esc(c.d.name)} — آخر هذه المهمة: ${c.last?new Date(c.last.start).toLocaleString('ar-DZ'):'لم يعمل'} — مرات: ${c.count}`).join('<br>')}</div>`:'لا يوجد متاح'}
function addAssignment(){const w=currentWeek();const m=missionById(document.getElementById('amission').value);const driverId=+document.getElementById('adriver').value;const role=document.getElementById('role').value;let start=document.getElementById('astart').value,end=document.getElementById('aend').value;if(m.id==='forest'){toast('للغابة استخدم الفترات المحددة وسجّل كل سائق كفترة مستقلة.');return}recordAssignment(w.id,m.id,driverId,new Date(start).toISOString(),new Date(end).toISOString(),role,document.getElementById('forestType').value,false,'');save();toast('تم تسجيل التوزيع')}
function weekTable(weekId){const xs=db.assignments.filter(a=>a.weekId===weekId).sort((a,b)=>new Date(a.start)-new Date(b.start));if(!xs.length)return '<div class="empty">لا توجد توزيعات فعلية.</div>';return `<div class="table-wrap"><table><thead><tr><th>السائق</th><th>اليوم</th><th>المهمة</th><th>الدور</th><th>من</th><th>إلى</th><th>راحة قبلها</th><th>استثناء</th></tr></thead><tbody>${xs.map(a=>{const d=db.drivers.find(x=>x.id===a.driverId),m=missionById(a.missionId),r=restBefore(a.driverId,a.start);return `<tr><td><b>${esc(d?.name)}</b></td><td>${m?.day}</td><td>${m?.name}</td><td>${esc(a.role||'—')}</td><td>${fmt(a.start)}</td><td>${fmt(a.end)}</td><td>${r?`${fmt(r.from)} → ${fmt(r.to)}<br><b>${r.hours.toFixed(1)} ساعة متصلة</b>`:'لا يوجد عمل سابق مسجل'}</td><td>${a.replacement?esc(a.reason):'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function fmt(x){return new Date(x).toLocaleString('ar-DZ',{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
function renderDrivers(){const el=document.getElementById('drivers');el.innerHTML=`<h2>السواق والحالة</h2><div class="table-wrap"><table><thead><tr><th>السائق</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${db.drivers.map(d=>`<tr><td>${esc(d.name)}</td><td><select data-status="${d.id}">${['متاح','عطلة','عجز طبي','مستعار'].map(s=>`<option ${s===d.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${d.status==='متاح'||d.status==='مستعار'?'متاح للتوزيع':'غير متاح'}</td></tr>`).join('')}</tbody></table></div>`;el.querySelectorAll('[data-status]').forEach(x=>x.onchange=()=>{db.drivers.find(d=>d.id===+x.dataset.status).status=x.value;save();})}
function renderHistory(){const el=document.getElementById('history');const rows=db.drivers.map(d=>{const xs=history(d.id);return `<div class="card"><h3>${esc(d.name)}</h3>${xs.length?xs.map(a=>{const m=missionById(a.missionId);const r=restBefore(d.id,a.start);return `<div class="driver-row"><div><b>${m?.name||a.missionId}</b><br><span class="small">${fmt(a.start)} → ${fmt(a.end)}</span></div><div><span class="pill">${a.role||'عادي'}</span>${a.forestType?`<span class="pill">${a.forestType}</span>`:''}${r?`<div class="rest">راحة: من ${fmt(r.from)} إلى ${fmt(r.to)} — <b>${r.hours.toFixed(1)} ساعة متصلة</b></div>`:''}</div></div>`}).join(''):'<div class="empty">لا يوجد سجل.</div>'}</div>`});el.innerHTML=`<h2>السجل والمقارنة</h2><p class="muted">يُعرض التاريخ كاملًا. لا يتم اختصار العدالة إلى أربعة أسابيع؛ يمكن استعمال الأسابيع الأخيرة للعرض فقط.</p><div class="grid">${rows.join('')}</div>`}
function renderFairness(){const el=document.getElementById('fairness');const m=missionById(document.getElementById('fairMission')?.value||'dunya');const cs=candidate(m.id);el.innerHTML=`<h2>من له الدور القادم؟</h2><div class="toolbar"><div class="field"><label>المهمة</label><select id="fairMission">${MISSIONS.map(x=>`<option value="${x.id}" ${x.id===m.id?'selected':''}>${x.seq}. ${x.name}</option>`).join('')}</select></div></div><div class="reason"><b>الأولوية الحالية: ${cs[0]?esc(cs[0].d.name):'لا يوجد سائق متاح'}</b><br><span class="small">الترتيب يعتمد على التاريخ الحقيقي للمهمة/الدور؛ من لم يعملها سابقًا يتقدم، ثم الأقدم، ثم عدد مرات العمل. الاستثناءات والعطلة والاستلاف يجب تسجيلها حتى تبقى في التاريخ.</span></div><div class="table-wrap"><table><thead><tr><th>الترتيب</th><th>السائق</th><th>آخر مرة في المهمة</th><th>عدد المرات</th><th>آخر عمل إجمالًا</th><th>الراحة منذ آخر عمل</th></tr></thead><tbody>${cs.map((c,i)=>`<tr><td>${i+1}</td><td><b>${esc(c.d.name)}</b></td><td>${c.last?fmt(c.last.start):'لم يعمل'}</td><td>${c.count}</td><td>${c.allLast?fmt(c.allLast.end):'—'}</td><td>${c.allLast?dur(new Date(c.allLast.end),new Date()).toFixed(1)+' ساعة':'—'}</td></tr>`).join('')}</tbody></table></div>`;document.getElementById('fairMission').onchange=renderFairness}
function renderAll(){renderDashboard();renderWeek();renderAssign();renderDrivers();renderHistory();renderFairness()}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sowa9-backup-${iso(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.drivers||!x.assignments)throw Error();db=x;save();toast('تم الاستيراد')}catch{toast('ملف غير صالح')}};r.readAsText(f)};
renderAll();
