const KEY='sowa9.v3';
const DAYS=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const DRIVERS=['زيباني','بغداد','بوسلاح','بلعربي','كاسي','زوالي'];
const BASE_STATUS={زيباني:'متاح',بغداد:'متاح',بوسلاح:'متاح',بلعربي:'متاح',كاسي:'عجز طبي',زوالي:'عطلة'};
const MISSIONS=[
{id:'dunya',name:'دنيا برك',seq:1,day:'الأحد',periods:[['12:00','22:00']],need:2,night:false,note:''},
{id:'garden',name:'غاردن سيتي',seq:2,day:'الأحد',periods:[['17:00','00:00']],need:2,night:true,note:''},
{id:'bahja',name:'البحر — بهجة',seq:3,day:'الثلاثاء',periods:[['09:00','22:00']],need:1,night:false,note:'خارجي ومتعب بسبب الحرارة؛ بهجة أصعب.'},
{id:'club',name:'البحر — كلوب',seq:4,day:'الثلاثاء',periods:[['12:00','22:00']],need:3,night:false,note:'خارجي ومتعب بسبب الحرارة.'},
{id:'bondage',name:'بونداج زرالدة',seq:5,day:'الأربعاء',periods:[['04:30','10:00']],need:2,night:false,note:''},
{id:'guard',name:'حراسة',seq:6,day:'الأربعاء',periods:[['17:00','00:00']],need:1,night:true,note:'داخلي ومريح، لكنه يُحسب عملًا ليليًا.'},
{id:'raids',name:'مداهمات',seq:7,day:'الخميس',periods:[['19:30','05:00']],need:2,night:true,note:'عمل خارجي ليلي.'},
{id:'delivery',name:'توصيل',seq:8,day:'الخميس',periods:[['20:00','21:30'],['06:30','08:00']],need:1,night:false,note:'فترتان منفصلتان.'},
{id:'barajat',name:'براجات',seq:9,day:'الجمعة',periods:[['06:00','12:00']],need:1,night:false,note:'داخلي ومريح.'},
{id:'forest',name:'الغابة',seq:10,day:'الجمعة',periods:[],need:4,night:false,note:'24 ساعة؛ أربعة سائقين. Alpha وMO لكل منهما سائق يعود في الفترة الثانية.'}
];
const FOREST={Alpha:{paired:[['بداية + نهاية','17:00','23:00','11:00','17:00']],single:[['وسط','05:00','11:00']]},MO:{paired:[['بداية + صباح','17:00','22:00','07:00','12:00']],single:[['نهاية','12:00','17:00']]}};
function fresh(){return {drivers:DRIVERS.map((name,i)=>({id:i+1,name,status:BASE_STATUS[name]})),weeks:[],assignments:[],loans:[],missed:[],events:[]}}
let db=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
db=Object.assign(fresh(),db); if(!db.drivers?.length)db.drivers=fresh().drivers;
function save(){localStorage.setItem(KEY,JSON.stringify(db));renderAll()}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function iso(d){return d.toISOString().slice(0,10)}
function sundayOf(s){const x=new Date(s+'T12:00');x.setDate(x.getDate()-x.getDay());return iso(x)}
function dateForDay(start,day){const x=new Date(start+'T12:00');x.setDate(x.getDate()+DAYS.indexOf(day));return iso(x)}
function fmt(v){return new Date(v).toLocaleString('ar-DZ',{dateStyle:'short',timeStyle:'short'})}
function hrs(a,b){return (new Date(b)-new Date(a))/3600000}
function mission(id){return MISSIONS.find(m=>m.id===id)}
function week(){return db.weeks[0]}
function active(){return db.drivers.filter(d=>['متاح','مستعار'].includes(d.status))}
function history(id){return db.assignments.filter(a=>a.driverId===id).sort((a,b)=>new Date(a.start)-new Date(b.start))}
function lastOverall(id){return history(id).at(-1)||null}
function lastFor(id,missionId,role='',forestType=''){return db.assignments.filter(a=>a.driverId===id&&a.missionId===missionId&&(!role||a.role===role)&&(!forestType||a.forestType===forestType)).sort((a,b)=>new Date(b.start)-new Date(a.start))[0]||null}
function restBefore(id,start){const h=history(id).filter(a=>new Date(a.end)<=new Date(start));if(!h.length)return null;const p=h.at(-1);return {from:p.end,to:start,hours:hrs(p.end,start),previous:p}}
function createWeek(start){start=sundayOf(start);if(db.weeks.some(w=>w.start===start)){toast('الأسبوع موجود');return}db.weeks.unshift({id:crypto.randomUUID(),start,createdAt:new Date().toISOString()});save();toast('تم إنشاء الأسبوع')}
function record(a){db.assignments.push({id:crypto.randomUUID(),createdAt:new Date().toISOString(),...a})}
function addMissed(weekId,missionId,driverId,reason){db.missed.push({id:crypto.randomUUID(),weekId,missionId,driverId,reason,resolved:false,date:new Date().toISOString()})}
function candidates(missionId,role='',forestType=''){
 return active().map(d=>{const exact=lastFor(d.id,missionId,role,forestType),same=lastFor(d.id,missionId),overall=lastOverall(d.id),missed=db.missed.filter(x=>x.driverId===d.id&&x.missionId===missionId&&!x.resolved).length;return {d,exact,same,overall,missed,count:db.assignments.filter(a=>a.driverId===d.id&&a.missionId===missionId).length}}).sort((a,b)=>{if(a.missed!==b.missed)return b.missed-a.missed;if(!a.exact&&!b.exact){if(!a.same&&!b.same)return a.d.id-b.d.id;if(!a.same)return -1;if(!b.same)return 1}if(!a.exact)return -1;if(!b.exact)return 1;const t=new Date(a.exact.start)-new Date(b.exact.start);if(t)return t;if(a.count!==b.count)return a.count-b.count;const ao=a.overall?new Date(a.overall.start).getTime():-Infinity,bo=b.overall?new Date(b.overall.start).getTime():-Infinity;return ao-bo})
}
function forestBase(w,type){return dateForDay(w.start,'الجمعة')}
function forestPairSegments(w,type){const base=forestBase(w,type),cfg=FOREST[type].paired[0];const a=new Date(`${base}T${cfg[1]}:00`),b=new Date(`${base}T${cfg[2]}:00`);b.setDate(b.getDate()+1);const c=new Date(`${base}T${cfg[3]}:00`),d=new Date(`${base}T${cfg[4]}:00`);c.setDate(c.getDate()+1);d.setDate(d.getDate()+1);return {first:{start:a,end:b},second:{start:c,end:d},label:cfg[0]}}
function forestSingle(w,type){const base=forestBase(w,type),cfg=FOREST[type].single[0];let s=new Date(`${base}T${cfg[1]}:00`),e=new Date(`${base}T${cfg[2]}:00`);s.setDate(s.getDate()+1);e.setDate(e.getDate()+1);return {start:s,end:e,label:cfg[0]}}
function forestSuggestion(type,kind){const role=kind==='paired'?FOREST[type].paired[0][0]:FOREST[type].single[0][0];return candidates('forest',role,type)}
function renderDashboard(){const w=week();document.getElementById('dashboard').innerHTML=`<h2>لوحة القيادة</h2><div class="grid"><div class="card"><h3>الأسبوع الحالي</h3><div class="metric">${w?esc(w.start):'—'}</div><p class="muted">الحساب يعاد لكل أسبوع، والسجل يبقى محفوظًا.</p></div><div class="card"><h3>المتاحون</h3><div class="metric">${active().length}</div></div><div class="card"><h3>التوزيعات</h3><div class="metric">${db.assignments.length}</div></div><div class="card"><h3>الاستلاف والتسليف</h3><div class="metric">${db.loans.length}</div></div></div><h3>الحالة الحالية</h3><div class="grid">${db.drivers.map(d=>`<div class="card"><b>${esc(d.name)}</b><p>${esc(d.status)}</p><span class="pill">${history(d.id).length} عمل تاريخي</span></div>`).join('')}</div>`}
function renderWeek(){const el=document.getElementById('week'),w=week();el.innerHTML=`<h2>الأسبوع</h2><div class="toolbar"><div class="field"><label>بداية الأسبوع (الأحد)</label><input type="date" id="newWeek" value="${w?.start||sundayOf(iso(new Date()))}"></div><button id="makeWeek">إنشاء أسبوع</button></div>${w?`<div class="table-wrap"><table><thead><tr><th>#</th><th>اليوم</th><th>المهمة</th><th>الفترة</th><th>المطلوب</th><th>ليلي؟</th><th>الوصف</th></tr></thead><tbody>${MISSIONS.map(m=>`<tr><td>${m.seq}</td><td>${m.day}</td><td><b>${m.name}</b></td><td>${m.id==='forest'?'Alpha: 17→23 + 05→11 + 11→17 / MO: 17→22 + 07→12 + 12→17':m.periods.map(p=>p.join('→')).join(' + ')}</td><td>${m.need}</td><td>${m.night?'نعم':'لا'}</td><td>${esc(m.note)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">أنشئ أول أسبوع.</div>'}`;document.getElementById('makeWeek').onclick=()=>createWeek(document.getElementById('newWeek').value)}
function renderAssign(){const el=document.getElementById('assign'),w=week();if(!w){el.innerHTML='<div class="empty">أنشئ أسبوعًا أولًا.</div>';return}const ds=active();el.innerHTML=`<h2>التوزيع الفعلي</h2><div class="card"><div class="toolbar"><div class="field"><label>المهمة</label><select id="amission">${MISSIONS.map(m=>`<option value="${m.id}">${m.seq}. ${m.name}</option>`).join('')}</select></div><div class="field" id="forestWrap" style="display:none"><label>نوع الغابة</label><select id="forestType"><option>Alpha</option><option>MO</option></select></div><div class="field" id="forestKindWrap" style="display:none"><label>الدور</label><select id="forestKind"><option value="paired">السائق الذي يعود مرة ثانية</option><option value="single">السائق الآخر</option></select></div><div class="field"><label>السائق</label><select id="adriver">${ds.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>استثناء/سبب</label><input id="reason" placeholder="اختياري"></div><button id="suggest">اقتراح حسب السجل</button><button id="addA">تسجيل التوزيع</button></div><div id="preview"></div></div><h3>توزيعات الأسبوع</h3>${weekTable(w.id)}`;
 const refresh=()=>{const m=mission(document.getElementById('amission').value),isF=m.id==='forest';document.getElementById('forestWrap').style.display=isF?'flex':'none';document.getElementById('forestKindWrap').style.display=isF?'flex':'none';document.getElementById('preview').innerHTML=isF?forestPreview(w):`<p class="muted">${esc(m.note)}</p>`};
 document.getElementById('amission').onchange=refresh;document.getElementById('forestType').onchange=refresh;document.getElementById('forestKind').onchange=refresh;refresh();
 document.getElementById('suggest').onclick=()=>{const m=mission(document.getElementById('amission').value);if(m.id==='forest'){const type=document.getElementById('forestType').value,kind=document.getElementById('forestKind').value,cs=forestSuggestion(type,kind);if(cs[0]){document.getElementById('adriver').value=cs[0].d.id;document.getElementById('preview').innerHTML=forestPreview(w,cs)}}else{const cs=candidates(m.id);if(cs[0]){document.getElementById('adriver').value=cs[0].d.id;document.getElementById('preview').innerHTML=reasonBox(cs)}}};
 document.getElementById('addA').onclick=()=>addCurrent(w)}
function forestPreview(w,cs){const type=document.getElementById('forestType')?.value||'Alpha',kind=document.getElementById('forestKind')?.value||'paired',p=kind==='paired'?forestPairSegments(w,type):forestSingle(w,type);const rows=cs||forestSuggestion(type,kind);return `<div class="reason"><b>${type}</b><br>${kind==='paired'?`${p.label}: ${fmt(p.first.start)} → ${fmt(p.first.end)}<br>ثم نفس السائق: ${fmt(p.second.start)} → ${fmt(p.second.end)}<br>راحة متصلة بينهما: ${hrs(p.first.end,p.second.start).toFixed(1)} ساعة`:`${p.label}: ${fmt(p.start)} → ${fmt(p.end)}`}<hr>${rows.slice(0,4).map((c,i)=>`${i+1}. ${esc(c.d.name)} — ${c.exact?`آخر هذا الدور ${fmt(c.exact.start)}`:'لا سجل لهذا الدور'} — ${c.same?`آخر الغابة ${fmt(c.same.start)}`:'لا سجل للغابة'}`).join('<br>')}</div>`}
function reasonBox(cs){return `<div class="reason"><b>المقترح: ${esc(cs[0].d.name)}</b><br>${cs[0].exact?`آخر نفس الدور: ${fmt(cs[0].exact.start)}`:'لم يعمل الدور من قبل.'}<br>${cs[0].same?`آخر نفس المهمة: ${fmt(cs[0].same.start)}`:'لم يعمل المهمة من قبل.'}<br><br>${cs.map((c,i)=>`${i+1}. ${esc(c.d.name)} — ${c.exact?fmt(c.exact.start):'لا سجل'} — مرات المهمة: ${c.count} — أدوار فائتة: ${c.missed}`).join('<br>')}</div>`}
function addCurrent(w){const m=mission(document.getElementById('amission').value),driverId=+document.getElementById('adriver').value,reason=document.getElementById('reason').value.trim();if(m.id==='forest'){const type=document.getElementById('forestType').value,kind=document.getElementById('forestKind').value,p=kind==='paired'?forestPairSegments(w,type):forestSingle(w,type),group=crypto.randomUUID();if(kind==='paired'){record({weekId:w.id,missionId:'forest',driverId,start:p.first.start.toISOString(),end:p.first.end.toISOString(),role:FOREST[type].paired[0][0],forestType:type,forestGroup:group,segment:1,replacement:!!reason,reason});record({weekId:w.id,missionId:'forest',driverId,start:p.second.start.toISOString(),end:p.second.end.toISOString(),role:FOREST[type].paired[0][0],forestType:type,forestGroup:group,segment:2,replacement:!!reason,reason})}else record({weekId:w.id,missionId:'forest',driverId,start:p.start.toISOString(),end:p.end.toISOString(),role:FOREST[type].single[0][0],forestType:type,forestGroup:group,segment:1,replacement:!!reason,reason});}else{const p=m.periods[0],s=new Date(`${dateForDay(w.start,m.day)}T${p[0]}:00`),e=new Date(`${dateForDay(w.start,m.day)}T${p[1]}:00`);if(p[1]<=p[0])e.setDate(e.getDate()+1);record({weekId:w.id,missionId:m.id,driverId,start:s.toISOString(),end:e.toISOString(),role:'',forestType:'',replacement:!!reason,reason})}save();toast('تم تسجيل التوزيع')}
function weekTable(id){const xs=db.assignments.filter(a=>a.weekId===id).sort((a,b)=>new Date(a.start)-new Date(b.start));if(!xs.length)return '<div class="empty">لا توجد توزيعات فعلية.</div>';return `<div class="table-wrap"><table><thead><tr><th>السائق</th><th>المهمة</th><th>الدور</th><th>الفترة</th><th>الراحة المتصلة قبلها</th><th>الاستثناء</th></tr></thead><tbody>${xs.map(a=>{const d=db.drivers.find(x=>x.id===a.driverId),m=mission(a.missionId),r=restBefore(a.driverId,a.start);return `<tr><td><b>${esc(d?.name)}</b></td><td>${m?.name}</td><td>${a.forestType?`${a.forestType} — ${a.role} — مقطع ${a.segment||1}`:'—'}</td><td>${fmt(a.start)}<br>→ ${fmt(a.end)}<br><b>${hrs(a.start,a.end).toFixed(1)} ساعة</b></td><td>${r?`${fmt(r.from)}<br>→ ${fmt(r.to)}<br><b>${r.hours.toFixed(1)} ساعة</b>`:'لا عمل سابق'}</td><td>${a.replacement?esc(a.reason):'—'}</td></tr>`}).join('')}</tbody></table></div>`}
function renderDrivers(){document.getElementById('drivers').innerHTML=`<h2>السواق والحالات</h2><div class="grid">${db.drivers.map(d=>`<div class="card"><h3>${esc(d.name)}</h3><select data-status="${d.id}"><option ${d.status==='متاح'?'selected':''}>متاح</option><option ${d.status==='عطلة'?'selected':''}>عطلة</option><option ${d.status==='عجز طبي'?'selected':''}>عجز طبي</option><option ${d.status==='مستعار'?'selected':''}>مستعار</option><option ${d.status==='مسلف'?'selected':''}>مسلف</option></select><p class="small">آخر عمل: ${lastOverall(d.id)?mission(lastOverall(d.id).missionId)?.name:'لا يوجد'}</p></div>`).join('')}</div><h3>الاستلاف والتسليف</h3><div class="card"><div class="toolbar"><div class="field"><label>السائق</label><select id="loanDriver">${db.drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select></div><div class="field"><label>النوع</label><select id="loanType"><option value="استلاف">استلاف من فرقة أخرى</option><option value="تسليف">تسليف لفرقة أخرى</option></select></div><div class="field"><label>الفرقة</label><input id="loanTeam" placeholder="اسم الفرقة"></div><div class="field"><label>المهمة</label><input id="loanMission" placeholder="المهمة"></div><button id="addLoan">حفظ</button></div><div>${db.loans.slice().reverse().slice(0,20).map(l=>`<div class="mission"><b>${esc(l.type)}</b> — ${esc(l.driverName)} — ${esc(l.team)} — ${esc(l.mission)}<br><span class="small">${fmt(l.at)}</span></div>`).join('')||'<p class="muted">لا يوجد سجل.</p>'}</div></div>`;document.querySelectorAll('[data-status]').forEach(x=>x.onchange=()=>{const d=db.drivers.find(d=>d.id==x.dataset.status);d.status=x.value;db.events.push({type:'status',driverId:d.id,status:d.status,at:new Date().toISOString()});save()});document.getElementById('addLoan').onclick=()=>{const d=db.drivers.find(d=>d.id==+document.getElementById('loanDriver').value);db.loans.push({id:crypto.randomUUID(),driverId:d.id,driverName:d.name,type:document.getElementById('loanType').value,team:document.getElementById('loanTeam').value.trim(),mission:document.getElementById('loanMission').value.trim(),at:new Date().toISOString()});save();toast('تم حفظ الاستلاف/التسليف')}}
function renderHistory(){const el=document.getElementById('history');el.innerHTML=`<h2>السجل والمقارنة</h2><p class="muted">التاريخ كامل. الحساب الأسبوعي يتجدد، لكن لا نحذف الأعمال السابقة. الراحة هي المدة المتصلة بين نهاية عمل وبداية العمل التالي.</p><div class="grid">${db.drivers.map(d=>{const hs=history(d.id).slice().reverse().slice(0,50);return `<div class="card"><h3>${esc(d.name)}</h3>${hs.length?hs.map(a=>{const m=mission(a.missionId),r=restBefore(d.id,a.start);return `<div class="mission"><strong>${m?.name}${a.forestType?' — '+a.forestType+' — '+a.role:''}</strong><div>${fmt(a.start)} → ${fmt(a.end)} (${hrs(a.start,a.end).toFixed(1)} ساعة)</div>${r?`<div class="rest">راحة متصلة: من ${fmt(r.from)} إلى ${fmt(r.to)} = <b>${r.hours.toFixed(1)} ساعة</b></div>`:''}</div>`}).join(''):'<p class="muted">لا يوجد سجل.</p>'}</div>`}).join('')}</div>`}
function renderFairness(){const el=document.getElementById('fairness');if(!week()){el.innerHTML='<div class="empty">أنشئ أسبوعًا أولًا.</div>';return}el.innerHTML=`<h2>الدور القادم</h2><p class="muted">الأولوية تعتمد على التاريخ الحقيقي، لا على نقاط مصطنعة. إذا كان السائق غير متاح فلا نعتبره أخذ دوره؛ يسجل الدور الفائت ويستمر الدور إلى المتاح.</p><div class="grid">${MISSIONS.filter(m=>m.id!=='forest').map(m=>{const cs=candidates(m.id),s=cs[0];return `<div class="card"><h3>${m.seq}. ${m.name}</h3><p>المقترح: <b>${s?esc(s.d.name):'لا يوجد متاح'}</b></p>${s?reasonBox(cs.slice(0,4)):''}</div>`}).join('')}<div class="card"><h3>10. الغابة</h3><p>Alpha — سائق يعود في نهاية المهمة + سائق وسط.</p><p>MO — سائق يعود صباحًا + سائق نهاية.</p><p class="small">راجع سجل Alpha/MO لكل سائق قبل تثبيت الدور.</p></div></div>`}
function renderAll(){renderDashboard();renderWeek();renderAssign();renderDrivers();renderHistory();renderFairness()}
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='sowa9-backup.json';a.click();URL.revokeObjectURL(a.href)};
document.getElementById('importBtn').onclick=()=>document.getElementById('importFile').click();document.getElementById('importFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{db=JSON.parse(r.result);save();toast('تم الاستيراد')}catch{toast('ملف غير صالح')}};r.readAsText(f)};renderAll();